### ISSUE TITLE
Enhancement: Support dialogs and stored conversation states in CustomBots

### ISSUE THREAD

**Issue by artokai** [pnp/generator-teams#10]
**Current behavior**

Currently the generated Custom Bot is basically just a Node Express handler which receives the posted message as input and returns a message back to the caller. Therefore the provided template does not support "long running" dialogs, stored conversation states or other services offered by the UniversalBot class.

**Enhancement idea**

Custom bots could be identical to the "Bot Framework" bots and support Dialogs and other services offered by the UniversalBot. 

This could be done  by writing a custom [IConnector](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iconnector.html) which would receive and parse the message from MS Teams and pass it on to the UniversalBot handler. The template could also utilize the provided [MemoryBotStorage](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.memorybotstorage.html)  to store the dialog state in memory, but the user could also write a custom implementation of [IBotStorage](https://docs.botframework.com/en-us/node/builder/calling-reference/interfaces/_botbuilder_d_.ibotstorage.html) to persist the state to a database etc..

Implementing a custom Connector should not be an impossible thing to do. The [Console Connector](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/ConsoleConnector.ts) included in the Bot Framework gives a nice starting point for it.
 
If you think that this would be a good idea and a way to go with the Custom Bot generator, then I could help out with implementing it.

**Comment by wictorwilen** [comment]
Thanks for the feedback @artokai, the idea is really cool, but I'm uncertain that it should be in the generator - this sounds more like a code example rather than boilerplate code, which is the intention of this generator. Thoughts?

**Comment by artokai** [comment]
I thought that this kind of thing could be part of the generator mostly because it would make bot development easier. Now you have to code your bot differently if you plan to register it as a "custom bot" in MS Teams. With a custom Connector the bot code could be same regardless of how you actually make it available (either register it to the bot framework service or add it as a "custom bot" to a team). 

But you're right about the code example -part. I should probably try to write an example first and if that proves out to be successful and a good way to write custom bots, then perhaps it can be incorporated in the generator itself.

**Comment by artokai** [comment]
I've done some more testing and it is actually possible to write a new connector that will allow you to use a "normal bot" and connect it to MS Teams using the "add custom bot" -feature. It does have some limitations but it works. I'll try to clean up my code a bit and post it somewhere soon.

But I now think the whole idea of "custom bots" is not to bypass the "Bot Framework Service" or the requirement to register your bots in it. The ability to add "custom bots" to MS Teams is also meant to allow people to bypass the whole "Bot Framework SDK" as well. And from that perspective, my suggestion of supporting Dialogs and such in the custom bots, doesn't really make sense.

So I think you should close this issue and file it into the pile of bad ideas. =)

**Comment by wictorwilen** [comment]
Yup, the intention for the Custom Bot is for users/devs who doesn't want to go the BotFx route. Essentially it's a webhook.
I'll close this but am looking forward to a code sample!
