### ISSUE TITLE
New project refactoring | code organization

### ISSUE THREAD

**Issue by andrewconnell** [pnp/generator-teams#100]
**Is your feature request related to a problem? Please describe.**

As discussed in our FEB13,2020 meeting, we'd like to optimize/improve the project organization. This issue serves to track the discussion... 

I'll propose a new project structure for review

*Feel free to assign to me*

**Comment by wictorwilen** [comment]
I'd recommend we look at how the Bot Fx generator creates deployment folders etc: https://github.com/Microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder

**Comment by wictorwilen** [comment]
Suggestion: what if we reorganized the repo in such way that it has the following foundational structure:
- `/` - readme etc
- `/docs` - documentation
- `/packages` - the actual package(s) used by the generator (see #107)
- `/packages/generator-teams` - the actual generator

**Comment by wictorwilen** [comment]
Done in 3.0.0 (#176)
