### ISSUE TITLE
Wrong TS errors; breaking compilation

### ISSUE THREAD

**Issue by paddotk** [pnp/generator-teams#102]
**Describe the bug**
When trying to run the app (locally), it fails when there are typescript errors:
```
 TS2322: Type '{ src: string; avatar: true; }' is not assignable to type '{}'.
  Property 'src' does not exist on type '{}'.
Unhandled rejection Error in plugin "webpack"
```
...
```
[11:43:09] The following tasks did not complete: serve, build, webpack, webpack:client, webpack:server
[11:43:09] Did you forget to signal async completion?
```

The problem here however is that:
1) There is nothing wrong with my code, also type-wise. This might be an issue with the npm package for which these errors are given, but whether the linter gives false errors or not, it should not break compilation of the app.
2) The later two errors insinuate something that has nothing to do with TS (in fact there errors aren't very clear to me).

**Detailed information**
 - Generator version: ? (latest, downloaded 20 feb 2020)
 - OS: Windows 10
 - Node version: 10.16.0
 - Npm version: 6.10.1

**Additional information**
The TS errors given are for a component of [https://microsoft.github.io/fluent-ui-react](https://microsoft.github.io/fluent-ui-react). I used just one component and am sure I properly implemented it. According to the TS linter in my code editor everything is right, according to the linter from the app runner it is not, apparently. Not sure whether this is because of the linter, or the fluent-ui library.

**Comment by wictorwilen** [comment]
Thanks @paddotk  for reaching out. I'd like some clarifications 
> When trying to run the app (locally), it fails when there are typescript errors:

Please share the actual code you've written. And can you verify that a generated vanilla project (a project without any customizations) compiles fine?

> Generator version: ? (latest, downloaded 20 feb 2020)

Preview version, or release version?

> The TS errors given are for a component of https://microsoft.github.io/fluent-ui-react.

If this is _not_ the preview version and you installed `@fluentui` did you install/uninstall any other npm packages?

> Not sure whether this is because of the linter, or the fluent-ui library.

A linter does not compile your source, it's essentially looking for "good practices" for writing/organizing your code.

**Comment by paddotk** [comment]
Hi,
I'm using the release version. No other npm packages were added or removed.

I setup a project (with just 'tab' as an option in the CLI), then added some code to the following file:
`src\app\scripts\yoteamsTestTab\YoteamsTestTab.tsx`

This file now looks like this. The parts between double asterisks are the bits of code I added (the rest is generated code):
```
import * as React from 'react';
import {
	PrimaryButton,
	TeamsThemeContext,
	Panel,
	PanelBody,
	PanelHeader,
	PanelFooter,
	Surface,
	getContext,
} from 'msteams-ui-components-react';
import TeamsBaseComponent, { ITeamsBaseComponentProps, ITeamsBaseComponentState } from 'msteams-react-base-component';
import * as microsoftTeams from '@microsoft/teams-js';
```
**
```
import {
	List,
	Image,
} from '@fluentui/react';
```
**
```
/**
 * State for the yoteamsTestTabTab React component
 */
export interface IYoteamsTestTabState extends ITeamsBaseComponentState {
	entityId?: string;
}

/**
 * Properties for the yoteamsTestTabTab React component
 */
export interface IYoteamsTestTabProps extends ITeamsBaseComponentProps {

}

/**
 * Implementation of the yoteams test Tab content page
 */
export class YoteamsTestTab extends TeamsBaseComponent<IYoteamsTestTabProps, IYoteamsTestTabState> {
	public componentWillMount() {
		this.updateTheme(this.getQueryVariable('theme'));
		this.setState({
			fontSize: this.pageFontSize()
		});

		if (this.inTeams()) {
			microsoftTeams.initialize();
			microsoftTeams.registerOnThemeChangeHandler(this.updateTheme);
			microsoftTeams.getContext((context) => {
				this.setState({
					entityId: context.entityId
				});
			});
		} else {
			this.setState({
				entityId: 'This is not hosted in Microsoft Teams'
			});
		}
	}

	/**
	 * The render() method to create the UI of the tab
	 */
	public render() {
		const context = getContext({
			baseFontSize: this.state.fontSize,
			style: this.state.theme
		});
		const { rem, font } = context;
		const { sizes, weights } = font;
		const styles = {
			header: { ...sizes.title, ...weights.semibold },
			section: { ...sizes.base, marginTop: rem(1.4), marginBottom: rem(1.4) },
			footer: { ...sizes.xsmall }
		};

		return (
```
**
```
			<div>
```
**
```

				<TeamsThemeContext.Provider value={context}>
					<Surface>
						<Panel>
							<PanelHeader>
								<div style={styles.header}>This is your tab</div>
							</PanelHeader>
							<PanelBody>
								<div style={styles.section}>
									{this.state.entityId}
								</div>
								<div style={styles.section}>
									<PrimaryButton onClick={() => alert('It worked!')}>A sample button</PrimaryButton>
								</div>
							</PanelBody>
							<PanelFooter>
								<div style={styles.footer}>
									(C) Copyright TestCompany
								</div>
							</PanelFooter>
						</Panel>
					</Surface>
				</TeamsThemeContext.Provider>
```
**
```
<div className="sidebar">
					<List selectable>
						<List.Item
							media={<Image src="/app/web/assets/icon.png" avatar />}
							header="Introductie adoption lead"
							selectable
							selected
						/>
					</List>
					</div>
					<div className="page-content contact">
					</div>
			</div>
```
**
```
		);
	}
}
```

Actually, now that I'm trying to run it again, even if I remove the earlier added code, it won't start at all. When I run `npm start` it just shows `> node dist/server.js` and gets stuck there.

**Comment by wictorwilen** [comment]
You say you are using the release version, have not added any npm packages, but you are referencing `@fluentui/react`? That doesn't make sense, since that package is only used in the latest preview and is a feature we're working on (#84), and you will get compatibility issues between dependencies due to this. If you want to use **fluentui** then use the latest preview version, otherwise resort to using components in `msteams-ui-components-react`.

**Comment by paddotk** [comment]
I meant other than _fluentui_, since I mentioned that in my first post. Sorry if that wasn't clear.

Thanks for the tip, I'll try the preview version. Do you have any rough indication of when the current preview version will become a release version?

**Comment by wictorwilen** [comment]
> Thanks for the tip, I'll try the preview version. Do you have any rough indication of when the current preview version will become a release version?

Any day now! 🤞

**Comment by paddotk** [comment]
@wictorwilen I've tried the preview version; I can run now the app but it does have an issue with the `@fluentui/react` lib, when I go to the generated tab page.

I also have a create-react-app application with fluentui which doesn't have this issue, so just in case it does have something to do with generator-teams, I'll post it here:

`Cannot read property 'telemetry' of undefined`
```
  var _useTelemetry = useTelemetry(List.displayName, context.telemetry),
      setStart = _useTelemetry.setStart,
      setEnd = _useTelemetry.setEnd;
```
in `node_modules/@fluentui/react/dist/es/components/List/List.js:21`

Any idea why this happens?

**Comment by paddotk** [comment]
Tried another project the same way, this time it works. Not sure why..

**Comment by wictorwilen** [comment]
@paddotk  - thanks for reporting back. I'll close this for now. If it happens again, feel free to re-open it.
