### ISSUE TITLE
Remove usage of the request module as its been deprecated

### ISSUE THREAD

**Issue by wictorwilen** [pnp/generator-teams#104]
**Is your feature request related to a problem? Please describe.**
The `request` npm module is deprecated

**Describe the solution you'd like**
Replace with modern alternative

**Describe alternatives you've considered**
`@azure/ms-rest-js` or `axios`

**Comment by andrewconnell** [comment]
I'd vote for axios... its more widely used by a factor of 4000x & is 20% the size of the MS option.

**Comment by wictorwilen** [comment]
See https://github.com/pnp/generator-teams/commit/1826a5cb80ffc420d582b07e3f2ade0ba7b429fd

**Comment by wictorwilen** [comment]
Fixed in https://github.com/pnp/generator-teams/tree/2.13.0
