### ISSUE TITLE
Unnecessary fontSize code in generated tab

### ISSUE THREAD

**Issue by pschaeflein** [pnp/generator-teams#106]
In the tsx file for a generated tab, the `componentWillMount()` method contains the following code that is unnecessary:

```tsx
this.setState({
  fontSize: this.pageFontSize()
});
```

**Comment by wictorwilen** [comment]
Thanks @pschaeflein, seems like a left over from the previous UX controls.

**Comment by wictorwilen** [comment]
See https://github.com/pnp/generator-teams/commit/093b4162e078ee2be238ba0721254ce05599b60e

**Comment by wictorwilen** [comment]
Fixed in https://github.com/pnp/generator-teams/tree/2.13.0
