### ISSUE TITLE
New flexible build system

### ISSUE THREAD

**Issue by wictorwilen** [pnp/generator-teams#107]
**Is your feature request related to a problem? Please describe.**
Currently the scaffolded project contains more or less hard coded Gulp tasks (in the `gulfile.js`). Updates or bug fixes to these are impossible to push out to already generated projects, unless we can force users to upgrade them through the generator - which also is a hard thing to do, if someone for instance has modified their gulp tasks. So, I want to support a more flexible build system (still based on Gulp) that allows us to update tasks and remain full flexibility for the developers.

**Describe the solution you'd like**
The idea is to publish the required gulp tasks as npm packages, which are dynamically read by the gulpfile at runtime. This allows for updates, full flexibility for devs to do their own thing and it aslo opens up an eco-system for custom build types (see #105 etc).

***Detailed solution proposal***

Replace the existing `gulpfile.js` with the following code, which uses the `gulp-load-plugins` to dynamically load all npm packages starting with `yoteams-`:

``` JavaScript
const { task } = require('gulp');
const config = require('./gulp.config');
const plugins = require('gulp-load-plugins')({
    pattern: ['yoteams-*'], // the glob(s) to search for
    scope: ['dependencies', 'devDependencies', 'peerDependencies'], // which keys in the config to look within
    replaceString: /^yoteams(-|\.)/, // what to remove from the name of the module when adding it to the context
});

Object.getOwnPropertyNames(plugins).forEach(name => {
    plugins[name](config);
});
```

Existing gulp tasks are then split into separate modules (`yoteams-build-core`, `yoteams-build-ngrok`...) and these modules look something like this, creating the required Gulp tasks for that build package:

``` JavaScript
const { task, src, dest } = require('gulp');

module.exports = (config) => {
  task('test-task', () => {
    return src(config.somewhere)
    .pipe(dest('output/'));
  });
};
```

This will then look like this when running `gulp --tasks`:
![image](https://user-images.githubusercontent.com/5854279/76068830-2b078b00-5f92-11ea-9f32-559982726435.png)

***Proposed build packages***
- `yoteams-build-core` - shared tasks needed (installs, client, server, manifest and serve below?)
- `yoteams-build-client` - client side build tasks (webpack, sass, inject)
- `yoteams-build-server` - server side build tasks
- `yoteams-build-serve` - serve and watch
- `yoteams-build-ngrok` - the ngrok serve
- `yoteams-build-manifest` - the manifest build and validation

**Describe alternatives you've considered**
Other solutions would be to use Rush, make the generator do the updates, split it up in multiple JS tasks files that manually can be updated (bundled into the solution).

**Comment by StfBauer** [comment]
It's a great idea but the complexity of this solution is not really useful. There is an easier option available that prolongs to the current generator too.

## Smaller build packages

One of the build packages could be simply defined as this:

```javascript
const {
    src,
    dest
} = require('gulp');

const firstGulpTask = () => {
    return src('./test/**')
        .pipe(dest('./test/'));
}

const secondGulpTask = () => {
    return src('./test/**')
        .pipe(dest('./test/'));
}

module.exports = {
    "first-gulp-task" : firstGulpTask,
    "second-gulp-task" : secondGulpTask
};
```

Alternatively, those could also be exported like this:

```javascript
module.exports = {
    firstGulpTask : firstGulpTask,
    secondGulpTask : secondGulpTask
};
```

## Central gulp file that just controls the flow

The `gulpfile.js` only then needs to control the flow and how and what gulp tasks need to be executed in which way.

```javascript
const {
    series,
} = require('gulp');
const gt1 = require('./gpt2');

exports.serve = series(gt1.firstGulpTask);
```

If a developer like to use any other build task, inject another one in between two build task. This can be easily done. The result of this setup is. Serve and watches should be in this gulp file too but no "real code" as it is now.

<img width="680" alt="Screenshot 2020-03-26 at 00 37 48" src="https://user-images.githubusercontent.com/5503835/77595673-1d428700-6efa-11ea-81c2-e649c323ddde.png">

So there is only one npm package needed but objects could be defined in a way like this.

```
yoteams.client.task1
yoteams.client.task2
...
yoteams.server.task1
yoteams.server.task2
...
yoteams.ngrok.task1
```

Those could then get imported to the gulp file like this:

```javascript
const client = require('yoteams/client')
const server = require('yoteams/server')
``` 

We could then use JSDoc to generate the documentation for the tasks. I also don't think it makes any sense to have multiple npm packages define that will be versioned in the same way anyway.

**Comment by wictorwilen** [comment]
Thanks for the input @StfBauer. What you suggest is a nice a good looking cleanup of the existing gulp file into multiple files and does not fulfill all of the goals outlined with the original suggestion. What I want to achieve is 

1) cleaner code (as you demonstrated) 
2) separation into more tasks oriented modules - where you suggest files in the project and the original suggestion is instead npm modules (or a combo of this). This allows us to update tasks after a project is scaffolded, for instance if a gulp task has an issue, new features are introduced etc. 
3) make it more lightweight - all  gulp tasks are not needed for all projects, see discussions on templating engine, there might be client side only Tabs, etc. And last but not least, 
4) we allow the devs to add/modify/remove stuff in the gulpfile without affecting any updates.

Keep the discussion going!

**Comment by StfBauer** [comment]
> 2. separation into more tasks oriented modules - where you suggest files in the project and the original suggestion is instead npm modules (or a combo of this). This allows us to update tasks after a project is scaffolded, for instance, if a gulp task has an issue, new features are introduced etc.

That is what versioning has been invented for. ;) It might look smart if you have sperate modules but in the end, you will have to upgrade all NPM modules to the same version or you will lose complete oversight.
If version 1.0 does not work well together with version 1.1 and Module A still uses 1.0 and Module B already is on 1.1. This lead to more problems than you actually aimed to avoid.

> 3. make it more lightweight - all gulp tasks are not needed for all projects, see discussions on templating engine, there might be client-side only Tabs, etc. And last but not least,

Gulp tasks defined in the NPM packages are the least concern cause the nearly need any space its is more about dependencies and those are also harder to control. You also need to consider what If I like to add extensions later on. The documentation can point out what references to add and how they need to be configured. Even thou in PNP/SPFx I have to support multiple frameworks they need different dependencies. Those are pretty hard to update and yet I found an easy solution for that, which is not yet automated but could be in future. It could lead to further be slimmed down.

> 4. we allow the devs to add/modify/remove stuff in the gulpfile without affecting any updates.

There is "no real code" in the gulp files as mentioned before only the workflow definition so you can add whatever you like even own custom gulp tasks in between two Microsoft Teams gulp task or replace for example the SASS build task with your own custom build task. The gulp file gets, even more, fill because it only has something like this in there.

```js
// Typescript compilation
const typescript = series(Task1, task2, task3);
// Serve dev servers
const server = series(Task1, typescript, task3);
// gulp serve
exports.serve = serve;
// gulp build
exports.build = typescript;
```

I don't really see how it do not fulfil your requirements - probably we should start to declutter the gulpfile first completely. ;)

**Comment by wictorwilen** [comment]
I do still believe separate modules, not controlled by the scaffolded project, is the correct way of doing this - if we still want to support running a generator over an existing project (which I think is hugely benefitial). Current update situation is very problematic - no matter how clean we make the gulpfile and its tasks.

**Comment by StfBauer** [comment]
It will be in future too cause Yeoman is not meant to re-run. 😃 

Updating an existing project does not work in SPFx either. The crucial part for a re-run is to drop TypeScript in general cause it does not really have any AST support that allows you to detect and especially update things such as the gulp file. I've been there with the PnP/SPFx generator and dropped it because it was pretty tricky.

We will see.

**Comment by wictorwilen** [comment]
You make my point, it's almost impossible to update the gulpfile the way it's done now, therefore moving them into separate entities will be better. 
Secondly we've been using AST to generate and update TypeScript files for the last two years in the generator - so I don't see that as an issue.

**Comment by waldekmastykarz** [comment]
What if each task was in its own file? If you want to update it, you overwrite all file contents and are done with it. You have the combination of separation of concerns, support of simple updates without having to fiddle with AST and without the complexity of separate npm packages. Yes, there are possible downsides:

1. Someone changes one of the existing tasks in the original file and an update will erase their changes - this can be addressed by docs
1. Someone adds another task to an existing file and again, update will erase their changes. Again something for the docs

You could even put the scaffolded tasks in a separate folder and create a separate folder for custom tasks.

**Comment by wictorwilen** [comment]
@waldekmastykarz - yea, that's been considered. The drawback of that is to update one of the build tasks - you are **required** to run the generator and overwrite or manually update the tasks. Sort of how it works today. I think a combination of "local" tasks and "published" tasks would be the ultimate combo. For instance - take the manifest validation, which requires a version and a schema. What if the manifest validation was a task that could be centrally updated when a new schema comes out and then used by everyone, instead of having everyone run the generator and overwrite their tasks (going through a git compare to find out what part of their customizations been updated).
This is the easy option however.

**Comment by waldekmastykarz** [comment]
With published tasks, wouldn't they need to update the corresponding npm package to use the new tasks? So in the end, wouldn't that be the matter of running `npm update` vs. re-running the generator?

What I like about packaging tasks is that it allows you to ensure the integrity of the tasks and easily update it. And if someone needs to adjust it, they can copy the code out of the tasks and create their local copy of it.

Another consequence is the maintenance of these tasks: would each of them be a separate repo or would you go down the route of a monorepo and publishing multiple npm packages from one repo? On the flip, if you use semver properly, it will allow you to update tasks independently without having to update the generator on each change.

I wonder to what extend distributing gulp tasks as npm packages is a common thing. If it is, then I rest my case and we should definitely go for it. If it's not such a common practice, then we should watch out for adding extra complexity.

**Comment by waldekmastykarz** [comment]
With published tasks, wouldn't they need to update the corresponding npm package to use the new tasks? So in the end, wouldn't that be the matter of running `npm update` vs. re-running the generator?

What I like about packaging tasks is that it allows you to ensure the integrity of the tasks and easily update it. And if someone needs to adjust it, they can copy the code out of the tasks and create their local copy of it.

Another consequence is the maintenance of these tasks: would each of them be a separate repo or would you go down the route of a monorepo and publishing multiple npm packages from one repo? On the flip, if you use semver properly, it will allow you to update tasks independently without having to update the generator on each change.

I wonder to what extend distributing gulp tasks as npm packages is a common thing. If it is, then I rest my case and we should definitely go for it. If it's not such a common practice, then we should watch out for adding extra complexity.

**Comment by StfBauer** [comment]
Understandable from the current state but for example the manifest "generator" as a generator I wouldn't do at all. (Just looked it up in code just now)

I would rather put it in a general library that can be consumed by all generators.

1:) Re-run of the generator can identify the re-run und just update the manifest using the library
2.) The code at all could be at some point may be called by CLI or Office 365 CLI
3.) Even if I re-run the generator and for example use a command switch like '--updatemanfest' I can skip the scaffolding.

Even for the future, you don't like to have generic until like update and write manifest. This could also be consumed by the gulp task.

The challenging thing is what should go in the gulp file and from my perspective only the core orchestration and not to much real code.

**Comment by wictorwilen** [comment]
@waldekmastykarz - yes it would require an `npm update`, that's the whole point. It's opt-in and it's more lightweight than running the generator over again (as that does more than just write over the files, such as upgrading manifest versions etc).

Sort of the design criteria's are:
- being able to update your ~~project~~ tasks without running the generator
- being able to not include all build tasks in your build pipeline if you don't need them - the case is I'm just building a bot for instance, or I only want to create a Tab
- having the option for you as developer to switch out and edit certain tasks (where have we heard this before :-))
- make it possible for us to use the node eco system, one example is templating system for pages (#105) - therefore we need to be able to add/remove gulp tasks. 
- being able to push updates/fixes to or add new tasks without having to re-publish a generator - having the tasks more loosely coupled from the generator
- future proof this

You mention the only caveat as I see this, and it's about how to maintain versions between tasks and generator. I think we can solve this in the same way as we're working with any other dependencies in the generator today, if there's a dependency that requires update, then we can update that (or recommend update). And of, course use semver properly.

With this in mind I think, creating atomic tasks is the best option (I think we all agree on this) and then publish these through some mechanism (where npm packages seems the most logic way)

As an example: Assume you would like to add Jade to your tabs, wouldn't it be great if you could make tasks for this and publish them, instead of having to create a PR to the generator and wait for all that to be completed.

Another example is in #113 - updating the "generator" to support this doesn't feel right. What if @StfBauer just created a `yoteams-sass-inline` task for this and published - through a custom repo, a community repo or a PnP repo...

**Comment by waldekmastykarz** [comment]
> being able to update your project without running the generator

This is a very specific requirement 😉 What's wrong with using the generator to upgrade the project? In this scenario I see the generator as an equivalent to let's say the ng or react CLI. You can run it as often as you need/want and it will do whatever you want it to. If you want it to create new stuff, it will. If you want it to update something specific, it will do just that. Do you see it differently?

> As an example: Assume you would like to add Jade to your tabs, wouldn't it be great if you could make tasks for this and publish them, instead of having to create a PR to the generator and wait for all that to be completed.

Wouldn't these tasks however need to be integrated in the generator (which would require a PR as well) at some point so that you can install them when scaffolding new project? Sure, you can install them manually, but isn't the whole point about convenience, like @StfBauer is doing in @pnp/spfx where you can pick what you want when scaffolding the project and all necessary deps will be installed for you?

**Comment by wictorwilen** [comment]
> This is a very specific requirement 

Correct, typo, should be *tasks* not project. Example, there's a "bug" in task. I can't ask or inform everyone to download a new generator version, go through the risk of running the generator (not all upgrade paths are happy paths), and then overwrite what we have. In this case, a patch version of that task could be published and all they have to do is to do npm update.

> Wouldn't these tasks however need to be integrated in the generator

That's the whole point. I do not want that. And this is how I do it today. 1) add my framework of choice 2) modify the gulp tasks. What if I only could do `npm install yoteams-jade-task` and it just works...

**Comment by wictorwilen** [comment]
And by all means - if someone wants to build another "extension generator" to add stuff, then go ahead. I would love it. I'd like to keep the yo teams as small as possible...

**Comment by waldekmastykarz** [comment]
> In this case, a patch version of that task could be published and all they have to do is to do npm update.

How would that work with lockfiles that are generated automatically nowadays? You could mark these packages as deprecated but with the number of dependencies in each project nowadays and the default number of warnings they could go unnoticed.

> That's the whole point. I do not want that.

Gotcha. Thanks for clarifying.

**Comment by wictorwilen** [comment]
> How would that work with lockfiles that are generated automatically nowadays? 

Spot on! I want to use an already known way. For instance how do you manage app insights updates for Office 365 CLI? You don't randomly just upgrade it, right? You control it - and that is the point. You are in command - not the generator. And as an example if there's a bug in a yo teams task and you're not bugged by it, you have no reason to update. If we had all of this bundled and scaffolded by the generator, then you would have no option to upgrade/overwrite or have stuff not working.

**Comment by waldekmastykarz** [comment]
> You don't randomly just upgrade it, right? You control it - and that is the point. You are in command - not the generator.

Correct, but I'd say it's rather out of necessity than by my own choice. Ideally, I'd love to automatically get latest patches and bugfixes. Unfortunately, the reality is that many devs don't quite adhere to semver and sometimes introduce breaking changes in versions marked as minor or patch. As a result we have lockfiles that isolate us from such breaking changes and put us in control but introduce additional maintenance effort to keep track of the state of all the different dependencies we use in our projects.

So perhaps, that's also another argument for using npm as it gives you a way to communicate the scope of the changes through the package version 👍

**Comment by wictorwilen** [comment]
Also a quick note. Having the core tasks as npm packages - does not prohibit you from adding Gulp tasks just as you normally would do; in the gulp file, as tasks files etc etc.

**Comment by andrewconnell** [comment]
_Catching up on the discussion..._ 

![](https://media.giphy.com/media/l2Sqc3POpzkj5r8SQ/giphy.gif)

I like where this is going... I do want to add a few things

@waldekmastykarz [asked](https://github.com/pnp/generator-teams/issues/107#issuecomment-614810785):
> What if each task was in its own file? 

I'm not a fan of this... my team did this on a product we were working on years ago and it was a nightmare to maintain. In theory, it was awesome (dynamically loading all tasks in a well-known folder), but in practice, it sucked across multiple projects as the build system was effectively XCOPIED across all projects. Making one change was tedious.

I'd much favor doing this with separate NPM packages as the [OP proposes](https://github.com/pnp/generator-teams/issues/107#issue-576793358).

@waldekmastykarz [asked](https://github.com/pnp/generator-teams/issues/107#issuecomment-615141799):
> How would that work with lockfiles that are generated automatically nowadays?

Just version them... a new version of an NPM package fixes that on update. NPM's versioning already accounts for this, giving the developer the option to specify an explicit version, auto-upgrade patch/minor/major versions... it's in the developer's control.

@StfBauer [mentioned](https://github.com/pnp/generator-teams/issues/107#issuecomment-607464356):
> Yeoman is not meant to re-run.

I don't agree **at all** with this.

![](https://media.giphy.com/media/YOkrK8agZLEk2cXeLi/giphy.gif)

If that was the case, there's almost zero use for **.yo-rc**. I've worked with countless generators that use this model & see zero reasons why it should be excluded from consideration to ADD things to a project, but NOT to change things.

You *could* even use it project upgrades. The challenge is that the logic is complex so it's probably not a good idea.

**Comment by StfBauer** [comment]
@andrewconnell really this guy you compare me to this guy 🤦‍♂️

Despite the re-run is never mentioned in the documentation and '.yo-rc' the purpose is not for re-runs.

I am out.

**Comment by andrewconnell** [comment]
_That's not a comparison... it was just meant to be funny :) If anything, that would be me saying "no" :) If it was taken as a comparison, my bad... not at all intended that way._

I hope you don't drop out of the thread... you've got a lot of value to add. Just because I don't agree doesn't mean one of us is wrong. Just a difference of opinion.

**Comment by waldekmastykarz** [comment]
> Despite the re-run is never mentioned in the documentation and '.yo-rc' the purpose is not for re-runs.

@StfBauer any evidence to back it up? Not taking any sides, just curious if it's more than an opinion/feeling (which doesn't necessarily have to be less valuable).

**Comment by StfBauer** [comment]
On .yo-rc file you will find this in the documentation:

> Storing user configuration options and sharing them between sub-generators is a common task. For example, it is common to share preferences like the language (does the user use CoffeeScript?), style options (indenting with spaces or tabs), etc.
> These configurations can be stored in the .yo-rc.json file through the Yeoman Storage API. This API is accessible through the generator.config object.

While I agree it can and is used to re-run generator, it is not the primary purpose of those `.yo-rc.` files. 

Despite some picky details, its name is "The web scaffolding for modern web apps," not "project management tool for modern web apps". You will also nowhere stated in the documentation

> In case you need to re-run and add something to your new project do this ...

Also pickier it is named generator, not a manager 😀

Anyway, I agree with @andrewconnell that it works to do a re-run and its more an architectural decision if it runs bare NodeJS code or a generator, which you can control.

For adding a new web part, it would make sense to run a sub-generator that does the same already on first provisioning. It will re-use template files, and through the parameters, you can controls how this new asset gets generated.

For other things, it does not make sense such as update the manifest of a teams project. The files are already there, and you just manipulate existing files, nothing that Yeoman uses internally is relevant for that re-run or check. In this case from my perspective, it is better to have a standalone function outside of Yeoman and just will be called by Yeoman.

The overall question from my perspective is that there are clear criteria of what should goes in the generator and what should be outside of the generator. Notably, in the long run, we might be able to use the same code base for certain things in the Teams generator, pnp/SPFx generator, O365/CLI, ... you name it.

**Comment by StfBauer** [comment]
Example: PnP/SPFx and scaffolding
I only can apply things mostly on existing files. I cannot use the generators in-memory file system cause the data already have been committed to the file system.

All utilities to customize the project setup run ATM in an own library. Utilities can get called with the yeoman file system or regular NodeJS file handling. So the generators are just stripped down to a core workflow engine for project scaffolding, what Yeoman is.

In the end, it do not matter if you rerun yeoman or call a CLI or call yeoman that calls a CLI.

**Comment by wictorwilen** [comment]
Thanks all, but can we please put an end to the philosophical question on whether Yeoman can/should update projects.

Currently there are 1) no plans in switching out Yeoman for something else and 2) we will continue to support adding new features to an existing project and when applicable and possible help the user to update their project.

**Comment by StfBauer** [comment]
0.) It is not philosophical it is architectural.
1.) No plans on switching out Yeoman - No one said that. Just some considerations on how to make life easier with Yeoman and when to use scaffolding and when not.
2.) Same here you can Yeoman to update and existing project and use technical nothing that yeoman offers in a generator - or you add a solid engine that allows you to update already scaffolded files via Yeoman.

**Comment by wictorwilen** [comment]
Gulp tasks moved into dedicated npm package with override options (#176)
