### ISSUE TITLE
gulp startup breaks because it doesn't understand css?

### ISSUE THREAD

**Issue by paddotk** [pnp/generator-teams#113]
**Describe the bug**
When I'm using any css in any .css (or .scss) file, I can't startup my project. Basically it looks like it (gulp?) doesn't understand how to parse those files.
It gives me errors like this:

```
[19:09:17] [Webpack error] ./src/app/scripts/myTab/index.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> * {
|       box-sizing: border-box;
|       padding: 0;
```
(This doesn't just apply to asterisks)

Then at the end I see
```
[19:09:18] The following tasks did not complete: serve, build, webpack, webpack:client
[19:09:18] Did you forget to signal async completion?
```
and it stops.

I must be doing something wrong, but I've no clue what it is. Any ideas?

**Detailed information**
 - Generator version: 2.12
 - OS: Windows 10
 - Node version: 12.14.1
 - Npm version: 6.13.4

**Additional information**
I'm not sure how relevant this is, but this issue I posted earlier might be related to some extent:
[https://github.com/pnp/generator-teams/issues/102](https://github.com/pnp/generator-teams/issues/102)

**Comment by wictorwilen** [comment]
Thanks @paddotk. I replicated the issue and what you need to do to get it to work is

1) Use SCSS and the `.scss` extension (the gulp tasks only look for scss files)
2) Do not add the CSS into `src/app/scripts/<tabname>` but instead add it under the tab folder in `src/app/web/<tabname>` (this is where your example goes wrong, if you're requireing the CSS)

This will properly create the CSS in the `./dist` folder. Then you can either manually link it in the HTML files or you can automatically inject in in all files by modifying the `injectSources` property of the `gulp.config.js` file so it looks like the following:
``` JavaScript
   injectSources: [
        "./dist/web/scripts/**/*.js",
        "./dist/web/**/*.css"
    ],
```
The alternative is to add the `SCSS` file to `/src/app/styles` which will do all of the above for you.

Or, modify the existing `main.scss` file.

Or, if you want to require the CSS in your TypeScript files, then you need to modify the `webpack.config.js` file to parse SCSS/CSS properly.

**Comment by paddotk** [comment]
Thanks @wictorwilen for the quick response and tips!

Is this a gulp or generator-teams thing? Seems a bit strange to me that regular .css files can't be used like that. Perhaps for a future version of generator-teams out-of-the-box support for css/scss could be added (so that they could stay in the same folder as components etc)? That would be great :)

Though putting my stylesheets in the `styles` folder works for me, this is not ideal IMHO. Less organised and could create issues with the order in which css rules are parsed (for generic styles and overrides, creating the need for `!important` flags in css rules).

I can't get figure out how to import these files from my React files. I've added supporting config code to webpack.config.js like you suggested.
Then trying the following one by one:
```
import '../../web/myTab/index.css';
import '/web/myTab/index.css';
import '/app/web/myTab/index.css';
import 'src/app/web/myTab/index.css';
```
the file can't be found ('Can't resolve' error). What is the right way to import these, assuming that the added snippets of webpack config are correct?
Although I don't think it's what's the problem here, this is what I added to my Webpack config file:
I added this to the Webpack config file:
```
modules: [
{
                  test: /\.module\.s(a|c)ss$/,
                  loader: [
                    isDevelopment ? 'style-loader' : MiniCssExtractPlugin.loader,
                    {
                      loader: 'css-loader',
                      options: {
                        modules: true,
                        sourceMap: isDevelopment
                      }
                    },
                    {
                      loader: 'sass-loader',
                      options: {
                        sourceMap: isDevelopment
                      }
                    }
                  ]
                },
                {
                  test: /\.s(a|c)ss$/,
                  exclude: /\.module.(s(a|c)ss)$/,
                  loader: [
                    isDevelopment ? 'style-loader' : MiniCssExtractPlugin.loader,
                    'css-loader',
                    {
                      loader: 'sass-loader',
                      options: {
                        sourceMap: isDevelopment
                      }
                    }
                  ]
                }
]
..
resolve: {
            extensions: [".ts", ".tsx", ".js", ".scss"],
}
```

**Comment by wictorwilen** [comment]
Got it, you want to import the CSS instead of using a global CSS. 

@StfBauer - you have any good ideas and input on how to make this smooth?

**Comment by StfBauer** [comment]
@paddotk can you share a demo project to look into as it seems from the past comments you have multiple issue that might be caused by the generator or your usage.

Also, it gives better insight on what things are missing and how to optimise. Thank you in advance.

**Comment by wictorwilen** [comment]
Closing due to no response. Feel free to open again.
