### ISSUE TITLE
Document update: Enabling Microsoft Teams Apps and sideloading

### ISSUE THREAD

**Issue by rabwill** [pnp/generator-teams#114]
I guess the documentation here for [Setup Tenant](https://github.com/pnp/generator-teams/wiki/Setup-Tenant) may be outdated. I had to go to the `Microsoft Teams admin center` to enable sideloading. This may be helpful to update for anyone new trying it out.
Thank you.

**Comment by wictorwilen** [comment]
@rabwill - thanks for noticing. Feel free to suggest an update by creating a pull request.

**Comment by rabwill** [comment]
Happy to take this up  ! Thank you

**Comment by wictorwilen** [comment]
Added to Wiki with 2.14.0
