### ISSUE TITLE
Deployment to azure fails due to Kudu not finding deploy.cmd

### ISSUE THREAD

**Issue by TetumTede** [pnp/generator-teams#115]
When trying to deploy a tab to azure Web app, I receive the following error message:
/opt/Kudu/KuduConsole/Scripts/starter.sh: line 2: exec: deploy.cmd: not found
/opt/Kudu/KuduConsole/Scripts/starter.sh: line 2: exec: deploy.cmd: not found\n/opt/Kudu/KuduConsole/Scripts/starter.sh deploy.cmd

I've been following the Readme instructions which comes with the code.

Steps to reproduce the behaviour:
1. Following the Git setup and deploy from the Readme
2. Within command prompt type "git push azure master"
3. Receive the error "/opt/Kudu/KuduConsole/Scripts/starter.sh: line 2: exec: deploy.cmd: not found"
4. The deployment fails

**Expected behaviour**
The deployment to azure should complete successfully but it fails.

**Screenshots**
![image](https://user-images.githubusercontent.com/18706666/78653943-bf2f7f80-78bb-11ea-8c32-25ad50a3136b.png)

**Detailed information**
 - Generator version: 3.1.0
 - OS: Windows 10
 - Node version: 10.16.3
 - Npm version: 6.9.0

**Comment by wictorwilen** [comment]
@tedumtede what version of the generator did you use? (3.1.0 is not a generator version number)

**Comment by TetumTede** [comment]
@wictorwilen Sorry that's the Yo version, Teams version is currently 2.13.0

**Comment by wictorwilen** [comment]
Thanks. 2.13.0 was just published, did you recreate your project with this brand new version one? Also, do you have a `deploy.cmd` in the root of your project?

**Comment by TetumTede** [comment]
No I hadn't as only updated it this morning when I noticed it could be updated, I've also updated the npm to 3.1.1. I'm just recreating what I did last time hopefully the update cures the issue. Yeah I do at the root level.

**Comment by TetumTede** [comment]
Well the update seems to of fixed the npm error! I'll update the thread once it has deployed and I've tested it in Teams
