### ISSUE TITLE
Additional Personal Tabs have the same entityId

### ISSUE THREAD

**Issue by leeford** [pnp/generator-teams#126]
**Describe the bug**
After the initial generation of the project, if you choose to generate an additional personal tab within the project (by using "yo teams" in the folder), it will create the new tab, but within the manifest.json file, the entityId of the tab is the same as initial tab created.

![image](https://user-images.githubusercontent.com/472320/84133652-542b3200-aa3f-11ea-8594-dcbcf232c640.png)

Upon loading the app in to Teams, no tabs will show. 

As per the manifest schema, the entityId field should be unique. If you make each entityId unique, they do show:

![image](https://user-images.githubusercontent.com/472320/84133807-863c9400-aa3f-11ea-892e-5df99cf99b37.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Under a previously created project, run "yo teams" again
2. When asked "What features do you want to add to your project?", select "A Tab"
3. When asked "What kind of Tab would you like to create?", select "Personal (static)"
4. Look under "staticTabs" in manifest.json and all tabs have the same entityId "default-data"

**Expected behaviour**
Each personal tab should have a unique entityId field.

**Detailed information**
 - Generator version: 2.14.0
 - OS: Windows
 - Node version: 10.20.1
 - Npm version: 6.14.5

**Comment by wictorwilen** [comment]
Thank you for reporting this. Will take a look at it ASAP

**Comment by wictorwilen** [comment]
A fix has been added to `2.15.0-preview2` if you want to test it now. Planned full release within a few days.

**Comment by leeford** [comment]
Yep, that works - a GUID is now present - thanks for the quick fix.
