### ISSUE TITLE
A typo in description - Wiki Documentation

### ISSUE THREAD

**Issue by kirti-prajapati** [pnp/generator-teams#128]
A typo in the description of "**Build a Connector for Microsoft Teams**".

Steps to find the typo:
1. Go to https://github.com/pnp/generator-teams/wiki/Build-a-connector-for-Microsoft-Teams
2. Scroll down to **Test the connector**
4. See the typo at "When the **proeject** was generated"

**Comment by wictorwilen** [comment]
Thanks for reporting this. Feel free to create a PR for this :-)

**Comment by kirti-prajapati** [comment]
Hi Wictor, Thanks for encouraging me to create a PR for this issue.
I have tried cloning the Wiki - https://github.com/pnp/generator-teams.wiki.git but not able to push the changes due to access issues.

Can you please advice how can I create a pull request for Wiki?

**Comment by hugoabernier** [comment]
@wictorwilen I tried to help @kirti-prajapati submit the PR, but we're both getting:

```
remote: Permission to pnp/generator-teams.wiki.git denied to hugoabernier.
fatal: unable to access 'https://github.com/pnp/generator-teams.wiki.git/': The requested URL returned error: 403
```

The typo is on line **80**

**Comment by wictorwilen** [comment]
Thanks @hugoabernier  and @kirti-prajapati . Seems like PR's to wikis is only for users with Write access to the repo. The recommended way to update a wiki is by clicking edit on the page itself (not doing a PR) and just edit away

**Comment by hugoabernier** [comment]
@wictorwilen thanks for your quick response but unfortunately, the ability to edit the wiki page doesn't appear for either @kirti-prajapati or I. Could it be a permissions thing?

**Comment by wictorwilen** [comment]
Hmm, I'll investigate...probably just another reason to move faster to MKDocs...

**Comment by wictorwilen** [comment]
I changed a setting to allow *public* editing of the Wiki, try it out please

**Comment by kirti-prajapati** [comment]
It works now. I have made the changes. Thanks for the quick response.
