### ISSUE TITLE
Package clash when SPFx is installed

### ISSUE THREAD

**Issue by ronaldborman** [pnp/generator-teams#130]
**Describe the bug**
Imho it's fair to assume that, just like myself, a majority of users will also have SPFx installed. When I install the prerequisites for the Teams generator, a package clash occurs:
```
npm ERR! code EEXIST
npm ERR! path ...\Roaming\npm\node_modules\gulp-cli\bin\gulp.js
npm ERR! dest ...\Roaming\npm\gulp
npm ERR! EEXIST: file already exists, cmd shim '...\Roaming\npm\node_modules\gulp-cli\bin\gulp.js' -> '...\Roaming\npm\gulp'
npm ERR! File exists: ...\Roaming\npm\gulp
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
```

**To Reproduce**
1. npm install gulp yo @microsoft/generator-sharepoint --global
2. npm install yo gulp-cli typescript --global

**Expected behavior**
A clash-free installation besides SPFx 

**Screenshots**

**Detailed information**
 - Generator version: 2.15.0
 - OS: Windows
 - Node version: v10.20.1
 - Npm version: 6.14.4

**Additional information**
I suspect the problem occurs because gulp-cli is already installed as part of the SPFx gulp installation. Perhaps inclusion of the --force argument is a solution, but it seems somewhat crude. If it is, than perhaps a note should be included in the installation documentation.

**Comment by wictorwilen** [comment]
Thanks for reporting this. Unfortunately the SPFX generator is using an old Gulp version from the V3 branch and for Yo Teams we're using Gulp V4.
We will not downgrade this for Yo Teams and we can wish for future SPFx versions to update their toolchain.

Personally I've not had any issues with running both generators, as any Gulp command executed will prefer to use the local Gulp version.

Another option if you want to avoid this is to use **npx**.
