### ISSUE TITLE
Problems trying to debug using VS Code

### ISSUE THREAD

**Issue by klippas-rob** [pnp/generator-teams#131]
I set breakpoints in my bot.ts file and when the debugger attaches, the red circles grey, and on mousing over any one of them I get the message "Unbound breakpoint".

I added this configuration to launch.json from README.MD, changing the port number to match gulp serve --debug:

 {
                "type": "node",
                "request": "attach",
                "name": "Attach,
                "port": 9229,
                "sourceMaps": true,
                "outFiles": [
                    "${workspaceRoot}/dist/**/*.js"
				],
                "remoteRoot": "${workspaceRoot}/src/"
}

In the terminal I run **gulp serve --debug** and Node runs with the debugger:

**Debugger listening on ws://127.0.0.1:9229/03a6f621-1c30-4a59-9211-11d77532c7fa**

I run the debugger in VS Code and the following appears in the DEBUG CONSOLE:

**Could not read source map for file:///Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/botbuilder-teams-messagingextensions/lib/index.js: ENOENT: no such file or directory, open '/Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/botbuilder-teams-messagingextensions/lib/index.js.map'
Could not read source map for file:///Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/@microsoft/recognizers-text-number/dist/recognizers-text-number.umd.js: ENOENT: no such file or directory, open '/Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/@microsoft/recognizers-text-number/dist/recognizers-text-number.umd.js.map'
Could not read source map for file:///Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/@microsoft/recognizers-text-suite/dist/recognizers-text-suite.umd.js: ENOENT: no such file or directory, open '/Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/@microsoft/recognizers-text-suite/dist/recognizers-text-suite.umd.js.map'
Could not read source map for file:///Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/@microsoft/recognizers-text-choice/dist/recognizers-text-choice.umd.js: ENOENT: no such file or directory, open '/Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/@microsoft/recognizers-text-choice/dist/recognizers-text-choice.umd.js.map'
Could not read source map for file:///Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/@microsoft/recognizers-text-date-time/dist/recognizers-text-date-time.umd.js: ENOENT: no such file or directory, open '/Volumes/Lakshmi/Users/rob/Documents/Klippas/Development/kippa2/node_modules/@microsoft/recognizers-text-date-time/dist/recognizers-text-date-time.umd.js.map'**

Moving the cursor over a breakpoint yields the message "Unbound breakpoint".

**Expected behavior**
Debugger launches without errors and breakpoints work.

**Detailed information**
 - Generator version: 2.15.0
 - OS: MacOS 10.15.5
 - Node version: 10.14.1
 - Npm version: 6.4.1

I am an experienced programmer, but new to Node and Javascript.

**Comment by schweigerandreas** [comment]
Hi Rob,

I had the same issue (not a Node and Javascript pro either).
For me running the command `npm run debug` fixed the problem. (I stumbled uppon this when looking at the package.json file.)

I hope that also works for you / others with the same problem.

**Comment by wictorwilen** [comment]
See #155
