### ISSUE TITLE
How can I get the deploy.cmd to run when deploying to Azure from VS Code?

### ISSUE THREAD

**Issue by T-Roth** [pnp/generator-teams#132]
How can I get the deploy.cmd to run when deploying to Azure from VS Code instead of Git?
My project is setup using v2.13.0 of the generator.

**Comment by wictorwilen** [comment]
This feature has been deprecated and Yo Teams does not longer support nor recommend this. I'd recommend that you use Azure DevOps or simliar for deployment of Yo Teams applications. See this as a reference: https://www.wictorwilen.se/blog/deploying-yo-teams-and-node-apps/
