### ISSUE TITLE
Debug server and client side code using VS Code

### ISSUE THREAD

**Issue by sandeepvootoori** [pnp/generator-teams#136]
Is it possible to debug server and client side code using VS Code while the app is running in teams using gulp ngrok-serve? 

**To Reproduce**
Below is my launch.json but seems like it only stops in server side code
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "args": [
                "ngrok-serve"
            ],
            "name": "start-ngrok",
            "program": "${workspaceFolder}/node_modules/gulp/bin/gulp.js",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node",
            "autoAttachChildProcesses": true,
        }
    ]
}

**Comment by wictorwilen** [comment]
Last time I tried Code does not allow for debugging both server and client side at the same time. I typically debug server side using Code and client side using Chrome/Edge dev tools.
