### ISSUE TITLE
Yo Teams fails when NordVPN enabled: ECONNREFUSED

### ISSUE THREAD

**Issue by westerdaled** [pnp/generator-teams#137]
**Describe the bug**

Luckily for me, figured this out pretty quickly as I happened to turn on the VPN earlier today. 

Go through the installation steps then run <code>yo teams</code>
```
What is your solution name? (learn-msteams-tabs) ApplicationInsights:CorrelationIdManager [ { Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443 } ]
```

**To Reproduce**

1. Install Teams Generator
2. Turn on NordVPN
3. Yo Teams
4. Turn off NordVPN
5. Repeat step3 and no issues

**Expected behavior**

**Screenshots*
![image](https://user-images.githubusercontent.com/937208/88402194-b14a2f80-cdc2-11ea-8764-5b4f58cb29ee.png)

**Detailed information**
 - Generator version: 2.15
 - OS: Windows 10
 - Node version: 12.8.3 ( tried 10.22.0)
 - Npm version: 6.14.6
- PowerShell Core 7.3 and Windows PowerShell 5.1

**Additional information**
This might be an issue with other VPNs / or firewalls.

**Comment by wictorwilen** [comment]
Thanks for this. This is our telemetry logging usage. Will add this to backlog to capture any errors correctly. Meanwhile, if you want to avoid this use the `--no-telemetry` flag when running `yo teams`.

**Comment by westerdaled** [comment]
Thanks @wictorwilen.   <code>--no-telemetry </code> flag  works perfectly.  Out interest, is there a way to list the command line arguments e.g. <code>yo teams --help</code>?

**Comment by wictorwilen** [comment]
`--help` will be there in a future update
