### ISSUE TITLE
I am not able to select " What features do you want to add to your project?" Even though i try to select bot , or webhook or connector. Tab is getting set automatically everytime. Can someone suggest a reason or workaround to fix this.

### ISSUE THREAD

**Issue by anmolsinghchauhan** [pnp/generator-teams#140]
**Describe the bug**
I am not able to select " What features do you want to add to your project?" Even though i try to select bot , or webhook or connector. Tab is getting set automatically everytime. Can someone suggest a reason or workaround to fix this.

**To Reproduce**
Run Yo Teams

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17361014/88968688-4c646d00-d2cd-11ea-85a8-cb87246b7281.png)

**Detailed information**
 - Generator version: [eg 2.5.0]
 - OS: [eg, Windows, MacOS]
 - Node version: [eg 8.10.0]
 - Npm version: [eg. 6.9.0]

**Additional information**

**Comment by anmolsinghchauhan** [comment]
Please help on this.

**Comment by wictorwilen** [comment]
Please verify the version of the generator - 2.5 is really old. Also if you're using the latest versions you need to upgrade node, as node 8 is no longer supported

**Comment by wictorwilen** [comment]
@anmolsinghchauhan  - have you been able to proceed?

**Comment by wictorwilen** [comment]
Closing this due to no response. Feel free to open again if the issue persists
