### ISSUE TITLE
Add additional documentation for deployment

### ISSUE THREAD

**Issue by richmondp** [pnp/generator-teams#141]
**Is your feature request related to a problem? Please describe.**
I am using the generator and Azure for the first time and I am trying to go through the instructions in the README.md for **Deploying to Azure using Git**. When it is asking to _Create a new *Web App* with Windows App Service Plan_ I am not sure what to do. On the Azure Portal the is a blade to create a Static Web App and one to create an App Service Plan but I am not sure how to create "a Web App with Windows App Service Plan". I have gone through the process of creating an App Service Plan but I can't seem to match up with the instructions. 

For example, when I create a new App Service Plan I can see the options *Configuration* -> *Application Settings*. 

Also, I can't find Deployment Center in the Azure Portal. 

See steps 4&5 of README.md -> Deploying to Azure using Git

**Describe the solution you'd like**
I would like the documentation to be expanded for people new to Azure like myself or at least a link to some documentation explaining it in more detail.

**Comment by RalfBrennscheidt** [comment]
Hello richmondp,

Microsoft branched out and named the bot specific service "Web App Bot" in Azure.
Please use this one instead.

Best regards,
Ralf B.

**Comment by wictorwilen** [comment]
We will make updates to the documentation in upcoming releases

**Comment by wictorwilen** [comment]
Removed the git deployment from latest release.
