### ISSUE TITLE
new DialogSet fails with botbuilder 4.10.1

### ISSUE THREAD

**Issue by klippas-rob** [pnp/generator-teams#142]
In the generated code, the new DialogSet fails if using botbuilder SDK 4.7.0 and above.

`	public constructor(conversationState: ConversationState) {
		super();

		this.conversationState = conversationState;
		this.dialogState = conversationState.createProperty('dialogState');
		this.dialogs = new DialogSet(this.dialogState);`

hovering over (this.dialogState) yeids the following error:

`	(property) Kippa7Bot.dialogState: StatePropertyAccessor<DialogState>
Argument of type 'import("…/Development/mybot/node_modules/botbuilder/node_modules/botbuilder-core/lib/botStatePropertyAccessor").StatePropertyAccessor<import("…/Development/mybot/node_modules/botbuilder-dialogs/lib/dialogContext").DialogState>' is not assignable to parameter of type 'import("…/Development/mybot/node_modules/botbuilder-core/lib/botStatePropertyAccessor").StatePropertyAccessor<import("…/Development/mybot/node_modules/botbuilder-dialogs/lib/dialogContext").DialogState>'.
  Types of property 'delete' are incompatible.
    Type '(context: import("…/Development/mybot/node_modules/botbuilder/node_modules/botbuilder-core/lib/turnContext").TurnContext) => Promise<...>' is not assignable to type '(context: import("…/Development/mybot/node_modules/botbuilder-core/lib/turnContext").TurnContext) => Promise<void>'.
      Types of parameters 'context' and 'context' are incompatible.
        Property 'bufferedReplyActivities' is missing in type 'import("…/Development/mybot/node_modules/botbuilder-core/lib/turnContext").TurnContext' but required in type 'import("…/Development/mybot/node_modules/botbuilder/node_modules/botbuilder-core/lib/turnContext").TurnContext'.ts(2345)
turnContext.d.ts(254, 14): 'bufferedReplyActivities' is declared here.
Peek Problem (⌥F8)
No quick fixes available`

**Expected behavior**
I had expected this not to have errors and that the generator would support the latest SDK

**Detailed information**
 - Generator version: 2.15.0 and 2.16.0-preview
 - OS: macOS 11.0
 - Node version: 10.14.1
 - Npm version: 6.14.8

**Comment by felipeplets** [comment]
I'm seeing the same error as @KIlippas-Rob

**Comment by wictorwilen** [comment]
This will be sorted in `2.16.0-preview2` and later

**Comment by wictorwilen** [comment]
Fixed in 2.16.0 preview 2
