### ISSUE TITLE
Deploy to Azure fails (App Service on Linux). 

### ISSUE THREAD

**Issue by latonita** [pnp/generator-teams#148]
**Describe the bug**
When I deploy generated app to Azure App Service (node/linux) it always fails.

**To Reproduce**
1. yo teams
2. open vscode
3. switch to Azure extension
4. deploy to existing Linux App Service
5. it makes zip file, uploads to azure and then
```
17:35:32 ep-test: Preparing deployment for commit id '8f0e489913'.
17:35:32 ep-test: Running custom deployment command...
17:35:33 ep-test: Not setting execute permissions for deploy.cmd
17:35:33 ep-test: Running deployment command...
17:35:33 ep-test: Command: deploy.cmd
17:35:34 ep-test: /opt/Kudu/Scripts/starter.sh: line 2: exec: deploy.cmd: not found
17:35:34 ep-test: /opt/Kudu/Scripts/starter.sh: line 2: exec: deploy.cmd: not found\n/opt/Kudu/Scripts/starter.sh deploy.cmd
17:35:37 ep-test: Deployment failed.
```
chaning .deployment file to use `deploy.sh` instead of `deploy.cmd` doesn't help. 

**Expected behavior**
Application deploys to App Service on Linux without any problem.

**Screenshots**

**Detailed information**
 - Generator version: 2.15
 - OS: both windows 10 and ubuntu
 - Node version: 10.22
 - Npm version: 6.14.6

**Additional information**

**Comment by rony2818** [comment]
You should delete deployment and deploy and re push again.
it worked for me

**Comment by wictorwilen** [comment]
Thanks for reporting this. The current `deploy.cmd` file is very old and will be deprecated in `2.16`+ in favor of updated documentation/methods, due to this and similar issues.
