### ISSUE TITLE
Integrating templates for more complex bots

### ISSUE THREAD

**Issue by billbliss** [pnp/generator-teams#15]
Wictor, today the bot portion of the generator template is pretty basic.

We've been working on a templatized version of a more complex bot we built. The GitHub project for the template is here: https://github.com/OfficeDev/microsoft-teams-template-bot and an example of it is here: https://teams.microsoft.com/l/chat/0/0?users=28:d75efef8-8a73-4b32-b7ad-9a05a7cff408.

Please take a look at the templates though - while I want there to be a more robust bot implementation, having these blank templates in place may be overkill. On the other hand, they don't take up a lot of space. The Yeoman generator itself wouldn't touch them, they would be, in essence, static files.

**Comment by billbliss** [comment]
Also, check out https://github.com/OfficeDev/microsoft-teams-generator-compose-extension. I would like to fold it into generator-teams but we also need to discuss scope (that example is pretty bare bones).

**Comment by wictorwilen** [comment]
This task is up for grabs!

**Comment by jakkaj** [comment]
We've been working on an enterprise ready version of the node bot template we call [bot boiler](https://github.com/MSFTAuDX/BotBoiler) - composable, testable, injectable etc - the real deal enterprise style boiler plate built on top of the regular bot builder. It might be of interest to have an enterprise option for the generator?

**Comment by cagdasdavulcu** [comment]
> This task is up for grabs!

@wictorwilen @billbliss: 
is there still a need for adding a complex bot application option into teams generator? I would be interested in extending of the teams generator.

**Comment by wictorwilen** [comment]
@cagdasdavulcu - yes, I do think so. Although, I would wait in putting to much effort into this until there is full support in teams for the latest botbuilder

**Comment by wictorwilen** [comment]
The current scaffolded bot shows some details and more complexity
