### ISSUE TITLE
Remove reference to bot's master in bot's default responses

### ISSUE THREAD

**Issue by BrendanAndrade** [pnp/generator-teams#152]
**Describe the bug**
By default the bot will respond with "I'm terribly sorry, but my master hasn't trained me to do anything yet..." when it receives a message that isn't "hello" or "help". 

**To Reproduce**
1. Send bot any message except hello or help.
2. Receive response "I'm terribly sorry, but my master hasn't trained me to do anything yet..."

**Expected behavior**
Bot should not reference a master/slave relationship. Suggest replacing master with developer in response text.

**Comment by wictorwilen** [comment]
Thank you for this. Very good suggestion - will fix this immediately to be included in the upcoming release!

**Comment by wictorwilen** [comment]
PR for this merged in 2.16 preview 2. Thanks
