### ISSUE TITLE
Error "TS1005: ';' expected." when calling gulp build on a new bot framework project

### ISSUE THREAD

**Issue by WillFrasier** [pnp/generator-teams#154]
**Describe the bug**
Followed instructions [here](https://github.com/PnP/generator-teams/wiki/Build-Your-First-Microsoft-Teams-App) and am seeing zillions of errors like this when I run the `gulp build` command. This was done on a machine with node and vs code install. It was a new bot project in a clean directory with no other content in it.

**To Reproduce**
`node and vs code already installed`
`npm install yo gulp-cli typescript --global`
`npm install generator-teams –global`
`yo (followed the prompts to create a bot project)`
![image](https://user-images.githubusercontent.com/9486825/95232865-e5c26a80-07b9-11eb-9b09-4102b23c6b9d.png)

`gulp manifest`
![image](https://user-images.githubusercontent.com/9486825/95233064-f1ae2c80-07b9-11eb-984b-1db98659d96e.png)

`gulp build`

**Expected behavior**
The project builds and I can run my bot project.

**Screenshots**
`gulp build` fails lots and lots of errors that look like the following (see screenshots)

![image](https://user-images.githubusercontent.com/9486825/95233166-f7a40d80-07b9-11eb-882e-c8e117486c5c.png)

```
[09:52:03] [Webpack error] C:\willf\git\edge.portal.1\edge.portal\bots\TelemetryBot\node_modules\@types\babel__traverse\index.d.ts
[tsl] ERROR in C:\willf\git\edge.portal.1\edge.portal\bots\TelemetryBot\node_modules\@types\babel__traverse\index.d.ts(529,27)
      TS1005: ';' expected.
```

**Detailed information**
 - Generator version: Not sure, what ever the latest is on 10/6/2020
 - OS: Windows
 - Node version: v12.14.1
 - Npm version: 6.13.4

**Additional information**

**Comment by niklasden** [comment]
Same issue here.
@WillFrasier did you find out how to fix this?


Generator version: 2.15.0 (latest version)
OS: PopOS! 20.04
Node version: 10.19.0
Npm version: 6.14.8

**Comment by wictorwilen** [comment]
Thanks fore reporting this. This issue is due to updated type definitions in Babel, which is installed by Jest, which is installed when you select to include tests. The Babel types has been updated and now requires Typescript > 3.4. 

**Your workaround is to run `npm install typescript@3.4 --save-dev`, to install a newer version of Typescript**

*Note: in upcoming version (2.16) the Typescript version will be updated (4.0.3)*
