### ISSUE TITLE
Debugging Server Side of Microsoft Teams App in Visual Studio Code isn't working

### ISSUE THREAD

**Issue by AmaniSakr** [pnp/generator-teams#155]
**Describe the bug**
Trying to debug the server code of Microsoft Team Tab, and the break point shows "unbound breakpoint" and the breakpoints doesn't get fired 
**To Reproduce**
1. Run gulp serve --debug after configuring the ngrok tunneling 
2. adjust the launch.json as following
`  {
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "port": 9229,
            "sourceMaps": true,
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "remoteRoot": "${workspaceRoot}/src/"
        }`
3. break points will be shown as "unbound breakpoint"
![image](https://user-images.githubusercontent.com/33348548/95727414-65e54600-0c7a-11eb-8370-89c0285c3f9c.png)

**Expected behavior**
that the break point can be fired
**Screenshots**
![image](https://user-images.githubusercontent.com/33348548/95727524-8b724f80-0c7a-11eb-9292-30c65a0c4cba.png)

**Detailed information**
 - Generator version: 2.15.0
 - OS: Windows
 - Node version: 10.22.1
 - Npm version: 6.14.6

**Additional information**

**Comment by wictorwilen** [comment]
This is what I use in VS Code for attaching my debugger:

```json
      {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "outFiles": ["${workspaceFolder}/dist/**/*.js"]
        },
```

Please try that.

**Comment by AmaniSakr** [comment]
Thanks a lot Wictor, This solved the debugging issue

**Comment by Marc93-14** [comment]
@AmaniSakr @wictorwilen are there any detailed steps on how to configure debugging? I don't currently have launch.json, when I create one which type do I choose? NodeJS? Nodejs legacy? 

I chose any type then copied pasted the code provided by @wictorwilen now I run gulp ngrok-serve --debug .. that doesn't do anything. Do I need to click F5 then to start debugging?

The steps in the readme aren't really complete, it just says run gulp serve --debug which doesn't run the ngrok process. Is there any decent documentation on how to configure debugging for yo teams?

**Comment by wictorwilen** [comment]
@Marc93-14 - see your OP for the answers: https://github.com/pnp/generator-teams/issues/221#issuecomment-851215809
