### ISSUE TITLE
Webpack error when importing PnPjs

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/generator-teams#158]
**Describe the bug**
Disclaimer: this is probably a user issue rather than a bug.

I am trying to implement [PnPjs](https://pnp.github.io/pnpjs/sp/) in a Teams solution. At build time Iam getting Webpack errors, here is an example:
```
[Webpack error] Module not found: Error: Can't resolve '../rest' in 'C:\My Git\Graph Access Test\node_modules\@pnp\sp\presets'
Did you mean 'rest.js'?
BREAKING CHANGE: The request '../rest' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**To Reproduce**
1. Generate a new yo Teams project (tab)
2. Install PnPjs: `npm i @pnp/sp`
3. Add import statements to the tab tsx file, for example:
`import { sp, Lists, ILists } from "@pnp/sp/presets/all";`
4. run `gulp ngrok-serve` and see the error

**Expected behavior**
Build runs without error.

**Detailed information**
 - Generator version: [eg 2.16]
 - OS: Windows, MacOS
 - Node version: 10.22.0
 - Npm version: 6.13.0

**Comment by wictorwilen** [comment]
@PathToSharePoint there seems to be an issue with the way PnPJs declares itself as a module and how Webpack 5+ resolves modules (there's a few reports on this in the Webpack repo). Have you tried the commonjs version of PnPJs?

**Comment by wictorwilen** [comment]
Closing this one due to comments on the PnPJs thread: https://github.com/pnp/pnpjs/issues/1461

This is not an issue with the yo teams scaffolded contents, rather how ESM modules are implemented in PnPJs.
