### ISSUE TITLE
Injection missing the css - With fix

### ISSUE THREAD

**Issue by weshackett** [pnp/generator-teams#16]
I've seen the tab html pages missing their css markup in the 'dist' folder.

I fixed this by changing a line in the gulpfile.js

var injectSources = ["./dist/web/scripts/**/*.js", "./dist/web/assets/**/*.css"]

**Comment by wictorwilen** [comment]
Thanks. Will look into it!

**Comment by weshackett** [comment]
Also noticed the hardcoded css element in the config and remove html files :)

**Comment by wictorwilen** [comment]
Fixed in the preview branch
