### ISSUE TITLE
gulp build is taking too long to build the whole process upon save

### ISSUE THREAD

**Issue by Vin-1991** [pnp/generator-teams#161]
**Describe the bug**
I'm facing an issue related to the building process of **gulp serve** and **gulp ngrok-serve.** Whenever i'm trying to save something it is taking 30 seconds to 2.5 min to build the whole process again and then only I will be able to see the changes on the screen.

**To Reproduce**
I'm using all the default files like **package.json** , **gulp.js**, **gulp.config.js** and **server.ts** which were created by the yo teams process.

**Expected behavior**
The process should take only some milliseconds to build the process in case of change detection but right now it is taking ages to complete it and unblock the page loading especially when there is change in the **.tsx** files. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/15855698/101618818-7c204000-3a38-11eb-8846-5a7096cb5977.JPG)

**Detailed information**
 - Gulp version: [4.0.2]
 - NG ROK version: [3.1.1]
 - Nodemon:  [2.0.4]
 - Node version: [v12.19.0]
 - Npm version: [6.14.8]

**Comment by wictorwilen** [comment]
Thanks @Vin-1991 - it's on our backlog to improve the build performance. We welcome any updates from the community to help with this. 
One thing you can do to optimize your build performance when debugging is to use the `--debug` flag to reduce optimizations done and to use the `--no-linting` to opt-out of linting.

**Comment by Vin-1991** [comment]
@wictorwilen I'm have already both(`--debug, --no-linting` ) of them in place  still it is taking this much time.

**Comment by wictorwilen** [comment]
@Vin-1991 - your compile times looks very long indeed, typically I see around 20-30 secs the first time and then around 10-30 secs depending on the size of the projects for incremental builds. There are a few things you can modify in `wepack.config.js` (one of the reasons we do share the full source of that one is so that you can modify it to your needs).

- set `transpileOnly: true` as an option in the `ts-loader` `options` option 
- set `devtool` to 'eval' ('source-map' is the slowest option)

These two takes rebuild times down to 2-4 seconds on a vanilla tab project

**Comment by Vin-1991** [comment]
@wictorwilen Thanks for the above recommendations. I have added both of them and it is now far better. For **`server`** it is taking **<= 1.5 sec** and for **`client`** it is taking **<= 25 seconds** in comparison to  minutes.

**Comment by wictorwilen** [comment]
That's great to hear! 25 seconds is still way above what I want it to be. Can you help me troubleshoot this a bit by doing the following:

1) run `npm install speed-measure-webpack-plugin` to install a webpack diagnostics tool
2) modify your `webpack.config.js` file to 
  a) in the beginning of the file have the following statement: `const SpeedMeasurePlugin = require("speed-measure-webpack-plugin");`
  b) in the second object in the `config` array (which is the client side configuration for webpack), make sure that second object is wrapped in `smp.wrap(...)`, so it looks like this: 
![image](https://user-images.githubusercontent.com/5854279/101738387-60fc1180-3ac6-11eb-9ec5-5b167fff263a.png)
3) post back the results of running `gulp webpack:client`

**Comment by Vin-1991** [comment]
Here are the results of server and client both.
![Capture](https://user-images.githubusercontent.com/15855698/101763913-6fb5e900-3b05-11eb-80c3-fcba4fc9a14e.JPG)

**Comment by wictorwilen** [comment]
Thanks. From what I've identified is that the by far largest issue with the client side code is that when the `@fluentui/react-northstar` library is included in a solution it really impacts build performance.

We'll keep iterating on this, to find the best possible configuration going forward.

**Comment by Lpt-wq** [comment]
@wictorwilen @Vin-1991 can you post an example of webconfig.js for the ts-loader settings? I changed the devtool and ran the gulp ngrok-serve with --no-linting and --debug, it takes around 90 seconds. How do I apply the ts-loader setting? 
am using generator version 3.

**Comment by appieschot** [comment]
@pnp/generator-teams-maintainers Since we merged #233 do we feel that we can close this one?

**Comment by wictorwilen** [comment]
Yes, closing.
