### ISSUE TITLE
CSS are not loading for teams app (tab, connectors)

### ISSUE THREAD

**Issue by piyumi25** [pnp/generator-teams#162]
I created apps using yeoman generator and previously it had nice CSS (fluent-ui package) but since from last week when I was generating apps, no CSS are applied to the app. Apps are loading without CSS.

The following is for connector app

 
![image](https://user-images.githubusercontent.com/33615108/101902284-6b0e3500-3bd8-11eb-95b2-a53dfcdf9834.png)

Can some one guide me to overcome from the issue?

**Comment by wictorwilen** [comment]
@piyumi25  - can you please provide what version of the generator you used to scaffold this project? By the looks of the icon it's at least a few versions old - and there's been quite a few changes in what UX package we're using (switched to @fluentui/react-northstar)

**Comment by wictorwilen** [comment]
@piyumi25 - also can you please run this `npm list --depth=0` in your project folder and share the details of that output

**Comment by piyumi25** [comment]
> npm list --depth=0

This is the output


```
PS C:\DEV\ConnectorAppNode> npm list --depth=0

┌─────────────────────────────────────────────────────────────┐
│                   npm update check failed                   │
│             Try running with sudo or get access             │
│            to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\fffff\.config │
└─────────────────────────────────────────────────────────────┘
connectorappnode@0.0.1 C:\DEV\ConnectorAppNode
+-- UNMET PEER DEPENDENCY @fluentui/react-northstar@0.49.0
+-- UNMET PEER DEPENDENCY @microsoft/teams-js@1.6.0
+-- @types/debug@4.1.2
+-- @types/express@4.16.0
+-- @types/express-session@1.15.10
+-- @types/morgan@1.7.35
+-- @types/node-json-db@0.0.1
+-- @types/react@16.8.10
+-- autoprefixer@9.8.6
+-- axios@0.19.2
+-- botbuilder@4.7.1
+-- botbuilder-dialogs@4.7.1
+-- browser-sync@2.26.13
+-- compression@1.7.4
+-- debug@4.1.1
+-- del@5.1.0
+-- dotenv@8.2.0
+-- dotenv-webpack@1.8.0
+-- express@4.16.4
+-- express-msteams-host@1.6.2
+-- express-session@1.15.6
+-- fancy-log@1.3.2
+-- file-loader@1.1.11
+-- gulp@4.0.2
+-- gulp-if@2.0.2
+-- gulp-inject@5.0.2
+-- gulp-load-plugins@1.6.0
+-- gulp-plumber@1.2.1
+-- gulp-postcss@8.0.0
+-- gulp-sass@4.1.0
+-- gulp-sourcemaps@2.6.5
+-- gulp-token-replace@1.1.5
+-- gulp-zip@4.2.0
+-- morgan@1.9.1
+-- msteams-react-base-component@2.2.0
+-- ngrok@3.3.0
+-- node-json-db@0.7.5
+-- nodemon@1.19.0
+-- plugin-error@1.0.1
+-- plumber@0.4.8
+-- react@16.14.0
+-- react-dom@16.14.0
+-- ts-loader@7.0.1
+-- tslint@5.20.1
+-- tslint-loader@3.6.0
+-- tslint-webpack-plugin@1.3.0
+-- typescript@3.3.4000
+-- typestyle@2.0.1
+-- vinyl@2.2.0
+-- webpack@4.26.0
+-- yargs@15.3.1
`-- z-schema@4.2.3

npm ERR! peer dep missing: @fluentui/react-northstar@^0.51.0, required by msteams-react-base-component@2.2.0
npm ERR! peer dep missing: @microsoft/teams-js@^1.8.0, required by msteams-react-base-component@2.2.0
```

**Comment by wictorwilen** [comment]
Take a look at the first two lines of that output:

```
+-- UNMET PEER DEPENDENCY @fluentui/react-northstar@0.49.0
+-- UNMET PEER DEPENDENCY @microsoft/teams-js@1.6.0
```

Please install the `@fluentiui/react-northstar` and `@microsoft/teams-js` packages.

How did you scaffold the project - only a connector?

**Comment by piyumi25** [comment]
> Take a look at the first two lines of that output:
> 
> ```
> +-- UNMET PEER DEPENDENCY @fluentui/react-northstar@0.49.0
> +-- UNMET PEER DEPENDENCY @microsoft/teams-js@1.6.0
> ```
> 
> Please install the `@fluentiui/react-northstar` and `@microsoft/teams-js` packages.
> 
> How did you scaffold the project - only a connector?

yes, only a connector

**Comment by wictorwilen** [comment]
Thanks, please verify that it works after you installed those packages and let me check if there might be an issue on the scaffolding side.

**Comment by piyumi25** [comment]
Thank you for your help, I will install them and let you know.

**Comment by piyumi25** [comment]
@wictorwilen I updated yeoman generator and it is able to fix my issue, Now no CSS issue.

**Comment by wictorwilen** [comment]
Thanks for the update!
