### ISSUE TITLE
Scaffold Teams tab app with SSO fails to install node-sass@4.14.1

### ISSUE THREAD

**Issue by dickiebowuk** [pnp/generator-teams#165]
I am trying to scaffold a tab app with SSO for teams. When it is scaffolding out the application it fails when installing packages. The process stops when it attempts to install node-sass@4.14.1.

**To Reproduce**
1. Complete Azure AD app registration
2. Create a new directory in Windows
3. Using cmd cd to new directory
4. yo teams
5. Select the following options:
- App Gen 2.17.1
- Create in current directory
- manifest v1.8
- Tab (application)
- Loading indicator on tab = Y
- Without header bar = Y
- Test Framework = N
- App Insights = N
- Configurable tab
- In a team
- SSO = Y
- Sharepoint = N

**Expected behavior**
I expected the scaffolded app to be created without any errors. I have tried several suggested solutions on the internet to fix it but nothing works. 

I installed the last version of node-sass (^5.0.0) and when I tried gulp ngrok-serve (with a valid ngrok account) it gives the same error with the dependency on version 4.14.1 and will not start.

**Screenshots**
Here is the end of the log file created when it fails:
33610 silly saveTree | +-- y18n@5.0.5
33610 silly saveTree | `-- yargs-parser@20.2.4
33610 silly saveTree `-- z-schema@5.0.0
33610 silly saveTree   +-- lodash.get@4.4.2
33610 silly saveTree   `-- validator@12.2.0
33611 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
33612 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
33613 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
33613 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
33613 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
33613 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
33614 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\glob-watcher\node_modules\chokidar\node_modules\fsevents):
33615 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
33616 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
33616 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
33616 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
33616 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
33617 warn @uifabric/utilities@7.33.2 requires a peer of @types/react-dom@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
33618 warn TestTabSSO@0.0.1 No repository field.
33619 warn TestTabSSO@0.0.1 No license field.
33620 verbose stack Error: node-sass@4.14.1 postinstall: `node scripts/build.js`
33620 verbose stack Exit status 1
33620 verbose stack     at EventEmitter.<anonymous> (C:\Users\windows.user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
33620 verbose stack     at EventEmitter.emit (events.js:315:20)
33620 verbose stack     at ChildProcess.<anonymous> (C:\Users\windows.user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
33620 verbose stack     at ChildProcess.emit (events.js:315:20)
33620 verbose stack     at maybeClose (internal/child_process.js:1021:16)
33620 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
33621 verbose pkgid node-sass@4.14.1
33622 verbose cwd C:\Users\windows.user\source\repos\TestTabSSO
33623 verbose Windows_NT 10.0.19042
33624 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\windows.user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--cache-min" "86400"
33625 verbose node v12.18.2
33626 verbose npm  v6.14.10
33627 error code ELIFECYCLE
33628 error errno 1
33629 error node-sass@4.14.1 postinstall: `node scripts/build.js`
33629 error Exit status 1
33630 error Failed at the node-sass@4.14.1 postinstall script.
33630 error This is probably not a problem with npm. There is likely additional logging output above.
33631 verbose exit [ 1, true ]

**Detailed information**
 - Generator version: [2.17.1]
 - OS: [Windows 10 Enterprise, Version: 20H2, OS build: 19042.685]
 - Node version: [12.18.2]
 - Npm version: [6.14.10]

**Comment by wictorwilen** [comment]
@dickiebowuk  - thanks for reporting this. I did a quick test with the same node version and could not replicate this. Have you been able to reproduce this multiple times?

**Comment by dickiebowuk** [comment]
Yes this has happened three times. Deleted the project, ran through the tutorial and get the same issue every time.

I’m happy to demonstrate it, if it would help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wictorwilen** [comment]
Thanks for the update. Would you mind sharing the full logs and the output from the console when scaffolding. Also detailed logs from `npm install node-sass --loglevel verbose` would be great if you could share.

**Comment by dickiebowuk** [comment]
Hi

Attached is the full log file produced from scaffolding the app. I ran the node-sass command below, but it didn’t produce a log file.

Best regards,
Richard Bowen

**Comment by dickiebowuk** [comment]
I captured the output from the cmd window when installing node-sass. The log is attached.

Best regards,
Richard Bowen

**Comment by dickiebowuk** [comment]
Attached is the cmd output when I attempt to scaffold the teams tab app.

Best regards,
Richard Bowen

**Comment by dickiebowuk** [comment]
I looked again at the errors when it was trying to install node-sass 4.14.1. npm couldn't hit the url and download the required files due to proxy settings for npm. I could download the files using chrome, so I could access it from my machine. I reset the proxy settings to null and tried again and the app scaffolded as expected and gulp ngrok-serve worked as well.
