### ISSUE TITLE
Separation of client and server code

### ISSUE THREAD

**Issue by sr258** [pnp/generator-teams#166]
The generator is really helpful to get started with developing a Teams app, but I'd like to know more about the reasoning behind the directory structure of the app. Client and server code is both put into the `app` directory. Most projects I've worked on separate code into a `server` and a `client` directory. What are the reasons that the generator produces a different structure?

**Comment by wictorwilen** [comment]
@sr258 - very valid question. The current structure is not optimal and we've kept it as this for *legacy* reasons. For V3 - there are two main objectives - the first one being making the build pipeline more flexible and better and secondly this exact issue. I'd love to get some feedback on how we could improve this. 

The current thinking is to change the directory structure into something like this. Any preferences or comments or thouhgts?
``` text
+ src
  + manifest (with support for subfolders for multiple environments/targets)
  + server (containing the server.ts file)
  + client (client side scripts)
  + web (static files, SCSS etc)
  + shared (optional for shared TypeScript artefacts)
```

**Comment by sr258** [comment]
I think your proposed structure makes a lot of sense.

**Comment by wictorwilen** [comment]
Done in 3.0.0 (#176)

**Comment by IshamMohamed** [comment]
Hi @wictorwilen - I have a question that after the scaffolding is done using this approach, (say I am scaffolding a Tab application with default tab named "Graph Tab") I can see `GraphTab.tsx` file which is consist of the  `GraphTab` component under "src/client/graphTab" directory, and I also can see `GraphTab.ts` file which is consist of the following code in "src/server/graphTab". 
```
import { PreventIframe } from "express-msteams-host";

/**
 * Used as place holder for the decorators
 */
@PreventIframe("/graphTab/index.html")
export class GraphTab {
}
```

What is the purpose / use-case of this additional file?

**Comment by wictorwilen** [comment]
@IshamMohamed - thank you for asking. The only purpose of this class (now) is to "host" the `PreventIframe` attribute, which sets a few HTTP headers to prevent iframing the tab outside of Teams (https://github.com/wictorwilen/express-msteams-host/blob/d2ca03ce6eea59cc2060e6742a42643a6cbc7897/src/routers/MsTeamsPageRouter.ts#L34)

**Comment by IshamMohamed** [comment]
Thank you for the clarification. I really appreciate it. I hope, we can continue to create any APIs (just routes) under "src/server/" directory so that we have a folder structure as below:
+ src
  + manifest (with support for subfolders for multiple environments/targets)
  + server (containing the server.ts file)
    + apis (contains the ts files for the routes)
  + client (client side scripts)
  + web (static files, SCSS etc)
  + shared (optional for shared TypeScript artefacts)
  
or do you recommend any other approach to have APIs.

**Comment by wictorwilen** [comment]
@IshamMohamed - that's exactly what's recommended!
