### ISSUE TITLE
Error occurred after publish the connector app 

### ISSUE THREAD

**Issue by piyumi25** [pnp/generator-teams#167]
I have created an office365 connector app using yeoman generator and it is working as expected when running it on ngrok. I published it in to Azure using VS code as a normal web application. When I am trying to configuring the connector I got following error and unable to configure.

![image](https://user-images.githubusercontent.com/33615108/103730925-f6c58680-5009-11eb-8ca6-2d2deaa00485.png)

**Comment by wictorwilen** [comment]
@piyumi25 - there was reports on this on other Teams repos a few weeks ago and last week I saw something about it being resolved. Can you please check again. What URL are you using to host your connector?

**Comment by wictorwilen** [comment]
Closing this as there's no response and no repo and discussions in Teams repo reports this working again
