### ISSUE TITLE
Error Error: Cannot find module 'C:\Dev\Teams\MyfirstYoTeamsApp\dist\server.js'

### ISSUE THREAD

**Issue by westerdaled** [pnp/generator-teams#168]
Seeing some strange issues with the currnent version of Yo Teams when attempting to scaffold and run two separate samples. I have included both as I think the issue is related

Issue 1) [My first teams App](https://github.com/pnp/generator-teams/wiki/Build-Your-First-Microsoft-Teams-App)
Tab App selected when running the generator

Issue 2)[Create an Action Command Message Extension](https://docs.microsoft.com/en-us/learn/modules/msteams-messaging-extensions/3-exercise-action-commands) 
No app selected in the generator  as per instructions

**To Reproduce**
Issue 1) ran through the steps outlined in the tutorial

Issue 2) again ran through the verbose steps in the tutorial

**Expected behavior**
I have used previous versions of the generator and not had any issues but not today!

Issue 1) Running gulp serve produces the following error

[MyfirstYoTeamsApp.errors.txt](https://github.com/pnp/generator-teams/files/5804772/MyfirstYoTeamsApp.errors.txt)

Issue 2)  Running gulp ngrok-serve produces the following error
[MessageExtTeamsApp.errors.txt](https://github.com/pnp/generator-teams/files/5804801/MessageExtTeamsApp.errors.txt)

**Screenshots**
Happy to add these on request

**Detailed information**
 - Generator version: 2.17
 - OS: windows 10
 - Node version: 14.15.4 
 - Npm version: 6.14
 - yo-CLI: 2.3
 - Yoeman: 3.1.1

**Additional information**

**Comment by westerdaled** [comment]
Working with my buddy: @simonDoy today , we've found that the generator needed to add these lines to the dependencies section of your package.json (after morgan)


   ```
 "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "react": "16.8.5",
    "react-dom": "16.8.5"
```

Not sure if this omission is a  result of unselecting the default  Tab App, As per  message Ext sample instructions. Anyway we now both able to look at those damn plannets in a 1:1 teams conversation 😃- you could saw we are over the moon!

**Comment by wictorwilen** [comment]
Thanks for reporting. I will try to replicate - those package references should be added by default.

**Comment by westerdaled** [comment]
@wictorwilen Were you able to replicate the issue as witnessed by @SimonDoy and I when working on the above Teams App challenge?

**Comment by wictorwilen** [comment]
@westerdaled - Issue 1 is likely due to that documentation adding a style namespace that does not exist in your file (old documentation, for an older version of the generator - if someone just had time to update those things), and nothing wrong with the generator itself.
Issue 2 is however a bug, introduced in 2.17, where in the case you create a messaging extension and do not choose to have a configuration page, then the react packages are not added. You already provided a workaround. Issue will be fixed in upcoming version 3.

**Comment by westerdaled** [comment]
@wictorwilen  Ah, I can take a hint 😏 . I am happy to volunteer to change the documentation: the way to heaven these days is one PR at a time.  Ok , so the issue 2 wasn't as result of unselected the default Tab App.  Thanks for looking into this.

**Comment by jimbobbennett** [comment]
Getting the same issue - working through [this Microsoft Learn module](https://docs.microsoft.com/en-us/learn/modules/msteams-conversation-bots/3-exercise-conversation-bots) and getting the error above. Adding the packages as suggested by @westerdaled above makes it work.

**Comment by wictorwilen** [comment]
This is fixed in v3 preview

**Comment by jayporta** [comment]
I'm using v4.0.1 and encountering the same issue.

```bash
❯ npm start

> test@0.0.1 start
> node dist/server.js

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/Users/jay/Developer/test-tab/dist/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

1) I followed the [steps in the tutorial](https://pnp.github.io/generator-teams/#installation)
2) Ran `npm install`
3) Ran `npm start`

**Comment by wictorwilen** [comment]
@jayporta  - the tutorial you link to just installs the generator. Did you run `yo teams` to scaffold a project? Also just running `npm start` will not build the project, just run it - and that's the error you're seeing `missing server.js`.
