### ISSUE TITLE
Error handling for dev and prod

### ISSUE THREAD

**Issue by NWH-SAmin5** [pnp/generator-teams#173]
Error handling for dev can be displayed in emulator
Error handling for prod can be log to Azure App Insights, OR to user

OR if there is already an example, please point me to it and I will close this.
Example of error handling for Teams Bot - generated using yo teams (NodeJS, Express)

**Comment by wictorwilen** [comment]
@NWH-SAmin5 thanks for reaching out. Can you please elaborate on what additional feature you need - there's already quite a bit of logging and support for Azure App Insights.

**Comment by NWH-SAmin5** [comment]
Hi @wictorwilen,

I am looking to use App Insights to log errors.
e.g. I am using Adaptive Card in Teams. I found out teams does not support large size / complex adaptive card and it shows generic error message "Oops! Something went wrong". I wanted catch this error and log it Azure App Insights.

This is one example, I am just generally looking to log any error thrown by the bot.

May be it already exists and I am not looking at right place

**Comment by wictorwilen** [comment]
Ok, this error typically happens through the chat bot. If you scaffold the project with AI settings this should already be set up for you. Also you can take a look at this node.js and AI tutorial: https://docs.microsoft.com/en-us/azure/azure-monitor/learn/nodejs-quick-start#:~:text=Quickstart:%20Start%20monitoring%20your%20Node.js%20Web%20application%20with,for%20Node.js%20to%20your%20application.%20More%20items...

**Comment by NWH-SAmin5** [comment]
@wictorwilen yes, its already setup I was able to find lot of information in Azure App Insights. I was able to also find the exact failed request I am looking for, but it does not have necessary error message to indicate what caused the issue. Generally, I would see stack trace or something... but these error doesnt log that. So wanted to log through error handling.

Documentation you mentioned through that I found, I could do something like this. So now, Is it possible to catch every error from Teams bot and log it using this

`client.trackEvent({name: "custom error", properties: {error: error}});`

```
let appInsights = require("applicationinsights");
appInsights.setup().start(); // assuming ikey in env var. start() can be omitted to disable any non-custom data
let client = appInsights.defaultClient;
client.trackEvent({name: "my custom event", properties: {customProperty: "custom property value"}});
client.trackException({exception: new Error("handled exceptions can be logged with this method")});
client.trackMetric({name: "custom metric", value: 3});
client.trackTrace({message: "trace message"});
client.trackDependency({target:"http://dbname", name:"select customers proc", data:"SELECT * FROM Customers", duration:231, resultCode:0, success: true, dependencyTypeName: "ZSQL"});
client.trackRequest({name:"GET /customers", url:"http://myserver/customers", duration:309, resultCode:200, success:true});

let http = require("http");
http.createServer( (req, res) => {
  client.trackNodeHttpRequest({request: req, response: res}); // Place at the beginning of your request handler
});
```

Looking for something like this..
Line 106
https://github.com/OfficeDev/microsoft-teams-sample-complete-node/blob/master/src/app.ts

OR

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-handle-user-interrupt?view=azure-bot-service-4.0&tabs=javascript#handle-unexpected-errors

**Comment by wictorwilen** [comment]
@NWH-SAmin5  - have you resolved your issue and can I close this one?

**Comment by NWH-SAmin5** [comment]
@wictorwilen - actually not exactly what I was looking for... but handling in a different way.. you can close it.... BUT
if you can take a look at Line 106 here
https://github.com/OfficeDev/microsoft-teams-sample-complete-node/blob/master/src/app.ts

That's what I am looking to do

If something like that is not possible then its fine

**Comment by wictorwilen** [comment]
@NWH-SAmin5 -  that's fairly simple to do. just do an `express.use(...)` in `server.ts` as one of the last statements before you start the server

**Comment by NWH-SAmin5** [comment]
@wictorwilen thank you for the suggestion, I havent got chance to try this yet.. so I will close this, will report back my results though
