### ISSUE TITLE
Error in npm node-gyp when I run the yo teams command

### ISSUE THREAD

**Issue by aldogarciaglez** [pnp/generator-teams#175]
**Describe the bug**
When I run the `yo teams` command and I provide the prompted information, I am getting the following error and it does not let me to continue:

7076 error code 1
7077 error path C:\Projects\MS600\learn-msteams-bot\node_modules\node-sass
7078 error command failed
7079 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
7080 error Building: C:\Program Files\nodejs\node.exe C:\Projects\MS600\learn-msteams-bot\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
7081 error gyp info it worked if it ends with ok
7081 error gyp verb cli [
7081 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
7081 error gyp verb cli   'C:\\Projects\\MS600\\learn-msteams-bot\\node_modules\\node-gyp\\bin\\node-gyp.js',
7081 error gyp verb cli   'rebuild',
7081 error gyp verb cli   '--verbose',
7081 error gyp verb cli   '--libsass_ext=',
7081 error gyp verb cli   '--libsass_cflags=',
7081 error gyp verb cli   '--libsass_ldflags=',
7081 error gyp verb cli   '--libsass_library='
7081 error gyp verb cli ]
7081 error gyp info using node-gyp@3.8.0
7081 error gyp info using node@15.8.0 | win32 | x64
7081 error gyp verb command rebuild []
7081 error gyp verb command clean []
7081 error gyp verb clean removing "build" directory
7081 error gyp verb command configure []
7081 error gyp verb check python checking for Python executable "C:\Python27amd64\python.exe" in the PATH
7081 error gyp verb `which` succeeded C:\Python27amd64\python.exe C:\Python27amd64\python.exe
7081 error gyp verb check python version `C:\Python27amd64\python.exe -c "import sys; print "2.7.18
7081 error gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
7081 error gyp verb get node dir no --target version specified, falling back to host node version: 15.8.0
7081 error gyp verb command install [ '15.8.0' ]
7081 error gyp verb install input version string "15.8.0"
7081 error gyp verb install installing version: 15.8.0
7081 error gyp verb install --ensure was passed, so won't reinstall if already installed
7081 error gyp verb install version is already installed, need to check "installVersion"
7081 error gyp verb got "installVersion" 9
7081 error gyp verb needs "installVersion" 9
7081 error gyp verb install version is good
7081 error gyp verb get node dir target node version installed: 15.8.0
7081 error gyp verb build dir attempting to create "build" dir: C:\Projects\MS600\learn-msteams-bot\node_modules\node-sass\build
7081 error gyp verb build dir "build" dir needed to be created? C:\Projects\MS600\learn-msteams-bot\node_modules\node-sass\build
7081 error gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
7081 error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
7081 error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
7081 error gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
7081 error gyp verb find vs2017   - Using this installation with Windows 10 SDK
7081 error gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
7081 error gyp verb build/config.gypi creating config file
7081 error gyp verb build/config.gypi writing out config file: C:\Projects\MS600\learn-msteams-bot\node_modules\node-sass\build\config.gypi
7081 error gyp verb config.gypi checking for gypi file: C:\Projects\MS600\learn-msteams-bot\node_modules\node-sass\config.gypi
7081 error gyp verb common.gypi checking for gypi file: C:\Projects\MS600\learn-msteams-bot\node_modules\node-sass\common.gypi
7081 error gyp verb gyp gyp format was not specified; forcing "msvs"
7081 error gyp info spawn C:\Python27amd64\python.exe
7081 error gyp info spawn args [
7081 error gyp info spawn args   'C:\\Projects\\MS600\\learn-msteams-bot\\node_modules\\node-gyp\\gyp\\gyp_main.py',
7081 error gyp info spawn args   'binding.gyp',
7081 error gyp info spawn args   '-f',
7081 error gyp info spawn args   'msvs',
7081 error gyp info spawn args   '-G',
7081 error gyp info spawn args   'msvs_version=2015',
7081 error gyp info spawn args   '-I',
7081 error gyp info spawn args   'C:\\Projects\\MS600\\learn-msteams-bot\\node_modules\\node-sass\\build\\config.gypi',
7081 error gyp info spawn args   '-I',
7081 error gyp info spawn args   'C:\\Projects\\MS600\\learn-msteams-bot\\node_modules\\node-gyp\\addon.gypi',
7081 error gyp info spawn args   '-I',
7081 error gyp info spawn args   'C:\\Users\\Aldo\\.node-gyp\\15.8.0\\include\\node\\common.gypi',
7081 error gyp info spawn args   '-Dlibrary=shared_library',
7081 error gyp info spawn args   '-Dvisibility=default',
7081 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Aldo\\.node-gyp\\15.8.0',
7081 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Projects\\MS600\\learn-msteams-bot\\node_modules\\node-gyp',
7081 error gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Aldo\\.node-gyp\\15.8.0\\<(target_arch)\\node.lib',
7081 error gyp info spawn args   '-Dmodule_root_dir=C:\\Projects\\MS600\\learn-msteams-bot\\node_modules\\node-sass',
7081 error gyp info spawn args   '-Dnode_engine=v8',
7081 error gyp info spawn args   '--depth=.',
7081 error gyp info spawn args   '--no-parallel',
7081 error gyp info spawn args   '--generator-output',
7081 error gyp info spawn args   'C:\\Projects\\MS600\\learn-msteams-bot\\node_modules\\node-sass\\build',
7081 error gyp info spawn args   '-Goutput_dir=.'
7081 error gyp info spawn args ]
7081 error gyp verb command build []
7081 error gyp verb build type Release
7081 error gyp verb architecture x64
7081 error gyp verb node dev dir C:\Users\Aldo\.node-gyp\15.8.0
7081 error gyp verb found first Solution file build/binding.sln
7081 error gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
7081 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
7081 error gyp info spawn args [
7081 error gyp info spawn args   'build/binding.sln',
7081 error gyp info spawn args   '/nologo',
7081 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
7081 error gyp info spawn args ]
7081 error gyp ERR! UNCAUGHT EXCEPTION
7081 error gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
7081 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
7081 error gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
7081 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:81:21)
7081 error gyp ERR! System Windows_NT 10.0.19041
7081 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Projects\\MS600\\learn-msteams-bot\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
7081 error gyp ERR! cwd C:\Projects\MS600\learn-msteams-bot\node_modules\node-sass
7081 error gyp ERR! node -v v15.8.0
7081 error gyp ERR! node-gyp -v v3.8.0
7081 error gyp ERR! This is a bug in `node-gyp`.
7081 error gyp ERR! Try to update node-gyp and file an Issue if it does not help:
7081 error gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
7081 error Build failed with error code: 7
7082 verbose exit 1

**To Reproduce**
I follow the following comands using npm:
`npm install yo gup-cli typescript --global`
`npm install generator-teams --global` & `npm install generator-teams@preview --global` 
`yo teams`

**Detailed information**
 - Generator version: [eg 2.5.0]
 - OS: Windows 10.0.19041 N/A Build 19041
 - Node version: 15.8.0
 - Npm version: 7.5.2
 - Python versions: 2.7.18, 3.9.1

**Additional information**
It always shows errors related to `node-sass` and `node-gyp` modules

**Comment by wictorwilen** [comment]
Thanks @aldogarciaglez - this seems to be an error with `node-gyp`, please see the link provided in the log https://github.com/nodejs/node-gyp/issues (specifically this one looks interesting https://github.com/nodejs/node-gyp/issues/2283)

**Comment by aldogarciaglez** [comment]
Thanks @wictorwilen!

It worked and now I was able to create the component with `yo teams`

I appreciate your response!
