### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by DomWill** [pnp/generator-teams#181]
Links are broken on page https://github.com/pnp/generator-teams for:

Documentation
The documentation for the generator and the generated project can be found in the generator-teams Github repository.

More information
For more information on how Tabs and Bots can be used with Teams see the Teams Developer Documentation

**Comment by wictorwilen** [comment]
@DomWill - thanks for reporting this!

**Comment by wictorwilen** [comment]
Fixed in #182
