### ISSUE TITLE
Errors on 'yo teams' (in very first question about  app  insights and after all questions answered error about northstar dependency)

### ISSUE THREAD

**Issue by alexabramkin** [pnp/generator-teams#183]
**Describe the bug**
Error on the 'yo teams' first in What is your solution name and then at the end of the process with northstar dependency

**To Reproduce**
1. Run 'yo teams'
2. See app insights error
3. Continue answering questions
2. Go through the process of answering questions
3. See northstar error

**Expected behavior**
Process finishing project creation

**Screenshots**

**Detailed information**
 - Generator version (`generator-teams`): [eg 3.0.2]
 - OS: [MacOS BigSur]
 - Node version: [eg 14.16.0]
 - Npm version: [eg. 7.6.0]

**Additional information**
**AppInsights error** in very first question
ApplicationInsights:CorrelationIdManager [
  Error: self signed certificate in certificate chain
      at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:467:12)
      at TLSSocket._finishInit (_tls_wrap.js:932:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  }
]
**Northstar dependency error**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ...@0.0.1
npm ERR! Found: @fluentui/react-northstar@0.52.1
npm ERR! node_modules/@fluentui/react-northstar
npm ERR!   @fluentui/react-northstar@"~0.52.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @fluentui/react-northstar@"^0.51.0" from msteams-react-base-component@3.0.2
npm ERR! node_modules/msteams-react-base-component
npm ERR!   msteams-react-base-component@"^3.0.2" from the root project
npm ERR!

**Comment by wictorwilen** [comment]
Thanks for reporting this. What's the result if you run `yo teams --no-telemetry`?

**Comment by alexabramkin** [comment]
No error in the first question(name), but still the same error about northstar dependency error at the end of answering questions/yoman run

**Comment by wictorwilen** [comment]
Thanks. 

For the application insights error I guess you have something blocking application insights (like Pi hole or a proxy of some kind). 

The second issue I just replicated - the way peer dependencies are handled has changed in npm 7+. You can work around the issue meanwhile by running `npm install --legacy-peer-deps` after you seen the error.

**Comment by alexabramkin** [comment]
Thank you Wictor. 

That works for the northstar package, granted that error happens during the process and command has to be run after:
- is there a way to tell if project was fully and correctly created given the dependency interruption (see all the choices and output for the sample project below)?

In other words can I use the generated project (after I run  "install @fluentui/react-northstar@"^0.51.0" --legacy-peer-deps") or creation of it was not fully  complete due to the error during the process of creation?

yo teams --no-telemetry

     _-----_     ╭──────────────────────────╮
    |       |    │ Welcome to the Microsoft │
    |--(o)--|    │    Teams App generator   │
   `---------´   │          (3.0.2)         │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What is your solution name? test
? Where do you want to place the files? Create a sub folder with solution name
? Title of your Microsoft Teams App project? test
? Your (company) name? (max 32 characters) ...
? Which manifest version would you like to use? v1.8
? Quick scaffolding Yes
? What features do you want to add to your project? A bot, A Message Extension C
ommand
? The URL where you will host this solution? https://test.azurewebsites.net
? Would you like show a loading indicator when your app/tab loads? Yes
? What type of bot would you like to use? A new bot Framework bot
? What is the name of your bot? test Bot
? What is the Microsoft App ID for the bot? It's found in the Bot Framework port
al (https://dev.botframework.com). 00000000-0000-0000-0000-000000000000
? Do you want to add a static tab to your bot? No
? Do you want to support file upload to the bot? No
? Do you want to include bot calling support? No
? Where is your message extension hosted? In a bot or Messaging Extension alread
y defined in this project
? What type of messaging extension command? Action based messaging extension
? What context do you want your action to work from? The compose box, The comman
d box
? How would you like to collect information from the user for your action? Using
 a Task Module
? Do you need configuration or authorization when collecting information? Yes
? Would you like a Settings option for the messaging extension? Yes
? What is the name of your Message Extension command? test Message Extension
? Describe your Message Extension command? Description of test Message Extension


    force ../.yo-rc.json
    force ../../../.yo-rc-global.json
    force .yo-rc.json
   create src/server/testMessageExtension/TestMessageExtension.ts
   create src/manifest/manifest.json
   create README.md
   create gulpfile.js
   create package.json
   create .env
   create src/server/server.ts
   create webpack.config.js
   create src/client/client.ts
   create src/public/index.html
   create src/public/tou.html
   create src/public/privacy.html
   create .gitignore
   create .eslintignore
   create .eslintrc.json
   create src/server/.eslintrc.json
   create src/client/.eslintrc.json
   create src/server/tsconfig.json
   create src/client/tsconfig.json
   create src/manifest/icon-outline.png
   create src/manifest/icon-color.png
   create src/public/assets/icon.png
   create src/public/styles/main.scss
   create src/server/TeamsAppsComponents.ts
   create Dockerfile
   create README-testBot.md
   create src/server/testBot/TestBot.ts
   create src/server/testBot/dialogs/HelpDialog.ts
   create src/server/testBot/dialogs/WelcomeCard.json
   create src/server/testBot/dialogs/WelcomeDialog.ts
   create src/client/testMessageExtension/TestMessageExtensionConfig.tsx
   create src/public/testMessageExtension/config.html
   create src/client/testMessageExtension/TestMessageExtensionAction.tsx
   create src/public/testMessageExtension/action.html
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test@0.0.1
npm ERR! Found: @fluentui/react-northstar@0.52.1
npm ERR! node_modules/@fluentui/react-northstar
npm ERR!   @fluentui/react-northstar@"~0.52.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @fluentui/react-northstar@"^0.51.0" from msteams-react-base-component@3.0.2
npm ERR! node_modules/msteams-react-base-component
npm ERR!   msteams-react-base-component@"^3.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/aabramkin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aabramkin/.npm/_logs/2021-02-28T18_04_36_314Z-debug.log

**Comment by wictorwilen** [comment]
Yes, the project should be correctly scaffolded, as the scaffolding and package installation are two discrete items. If you really want to be sure then you can run yo teams with `-skip-install`, which skips that last package install step and requires you to manually do it

**Comment by alexabramkin** [comment]
Very good to know, I will do that, thank you Wictor! Given there are workarounds closing this one now.

**Comment by wictorwilen** [comment]
Updated package for `msteams-react-base-component` that fixes this is also imminent
