### ISSUE TITLE
Support for generating Link Unfurling extensions

### ISSUE THREAD

**Issue by PaoloPia** [pnp/generator-teams#187]
I'd like to see Link Unfurling as one additional option when generating Messaging Extensions.
I already have a working sample that I will simply need to integrate with the generator.

**Comment by MTCMarkFranco** [comment]
I have built this using the 1.5 version of the generated project last March. I, too would like to see this in the generator.

**Comment by PaoloPia** [comment]
Here is the PR: https://github.com/pnp/generator-teams/pull/200 - Thanks.

**Comment by wictorwilen** [comment]
Added in #217
