### ISSUE TITLE
Typo in question for bot

### ISSUE THREAD

**Issue by pschaeflein** [pnp/generator-teams#191]
**Describe the bug**
When choosing to generate a bot, the user is prompted for the type of bot to use. The list of choices includes a Bot Framework bot. In the generator, the option is spelled with a lowercase 'b'. 

![image](https://user-images.githubusercontent.com/8008013/110244390-1acb1880-7f24-11eb-96f3-2b2275b67d29.png)

In Microsoft's documentation, an uppercase 'B' is used.

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0

**To Reproduce**

**Detailed information**
 - Generator version (`generator-teams`): 3.0.3
 - OS: Win10
 - Node version: 10.16.3
 - Npm version: 6.4.1

**Comment by wictorwilen** [comment]
Thanks @pschaeflein
