### ISSUE TITLE
Add message extension description in manifest

### ISSUE THREAD

**Issue by pschaeflein** [pnp/generator-teams#192]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When scaffolding a message extension, the user is prompted to describe the message extension command. This description is not added to the manifest. The description property in the manifest is "Add a clever description here".

**Comment by wictorwilen** [comment]
Thanks @pschaeflein, looking forward to a PR

**Comment by wictorwilen** [comment]
Thanks @pschaeflein
