### ISSUE TITLE
 Webhook for incoming calls Sample

### ISSUE THREAD

**Issue by cyril-iselin** [pnp/generator-teams#218]
Hello

Thanks for your great work!

Is there any sample how to implement [ Webhook for incoming calls ] ( @BotCallingWebhook("/api/calling") ) correctly?
How i transfer a call to another agent?

Best Greetings and thnaks!

**Comment by wictorwilen** [comment]
Hi @cyril-iselin - the documentation is available here https://github.com/wictorwilen/express-msteams-host#adding-support-for-calling-in-bots and then you have to implement as described in https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/call-notifications.

On the question to transfer to an agent that question should be asked in the bot framework communities/repos

**Comment by cyril-iselin** [comment]
Thanks for your answer. 

The documentation is really bad and I can't find *any* implementation for this method. 

There are some c# implementations but it looks like it works completly different.

**Comment by wictorwilen** [comment]
Yes, agree, it is not well documented and when I initially did this I had to reverse engineer every single command. And, the SDK available is only for .NET on Windows machines. Also a reason that this feature has not received that much love in the generator.

However, there might be changes to this area, not necessarily in this specific endpoint.

Closing this.
