### ISSUE TITLE
Generate manifest with schema version 1.0 

### ISSUE THREAD

**Issue by pschaeflein** [pnp/generator-teams#22]
The generated manifest uses v0.4 of the schema. The current schema version is 1.0.

Information on migrating is published at https://msdn.microsoft.com/en-us/microsoft-teams/schemamigrate

**Comment by wictorwilen** [comment]
@pschaeflein - the current release version is schema 0.4 because that's what's rolled out in GA. If you install the generator-teams@preview then you will get the 1.0 schema (see https://github.com/OfficeDev/generator-teams/blob/master/README.md for preview installation)

**Comment by pschaeflein** [comment]
Thanks. I was confused by the documentation, which does not mention GA/Beta status.
https://msdn.microsoft.com/en-us/microsoft-teams/schema
