### ISSUE TITLE
Support for Adaptive Card 1.4 version

### ISSUE THREAD

**Issue by nanddeepn** [pnp/generator-teams#226]
**Is your feature request related to a problem? Please describe.**
Create applications with adaptive cards for [user specific views](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/user-specific-views?tabs=mobile).

**Describe the solution you'd like**
I tried using Adaptive Card v1.4 with yo teams, but it does not render a button for action as `Action.Execute`

**Describe alternatives you've considered**
None

**Comment by wictorwilen** [comment]
Thanks @nanddeepn - great suggestion!

**Comment by nanddeepn** [comment]
Hi @wictorwilen 
Thank you. Please let me know, if I can be of any help in picking up this.
