### ISSUE TITLE
Feature Request: Use new GitHub issue template

### ISSUE THREAD

**Issue by appieschot** [pnp/generator-teams#231]
**Is your feature request related to a problem? Please describe.**
No, just feel that a clear format would help raising issues and feature requests 

**Describe the solution you'd like**
Implement: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository as is done in CLI (https://github.com/pnp/cli-microsoft365/tree/main/.github/ISSUE_TEMPLATE) 

**Describe alternatives you've considered**
N/a/

Feel free to assign to me

**Comment by wictorwilen** [comment]
Feel free to update the existing templates!
