### ISSUE TITLE
Feature request: Update scaffolded readme files with latest changes

### ISSUE THREAD

**Issue by appieschot** [pnp/generator-teams#236]
### 💡 Idea

We haven't updated the scaffolded readme files in a while. Based on the latest schema implementations we should update our readme files accordingly. 

### Is your feature related to a bug

No

**Comment by appieschot** [comment]
For future reference, readme file location: 
- packages/generator-teams/src/app/templates/README.md

References: 
- packages/generator-teams/src/custombot/CustomBotGenerator.ts
- packages/generator-teams/src/connector/ConnectorGenerator.ts
- packages/generator-teams/src/bot/BotGenerator.ts

We should update this file with the latest updates from schema references, and validate if our references needs updating as well.

**Comment by wictorwilen** [comment]
Individual readme files are removed, and replace with docs from v4.0.0
