### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by wictorwilen** [pnp/generator-teams#24]
Add documentation to the microsoft-teams-docs repository on how to use the generator

**Comment by pschaeflein** [comment]
I'll take this.

**Comment by wictorwilen** [comment]
Training and documentation on usage is now available in https://github.com/OfficeDev/TrainingContent

**Comment by pschaeflein** [comment]
What do you think of the structure of the docs folder in my repo: https://github.com/pschaeflein/generator-teams/tree/preview/docs

I can submit a PR with the Teams section this week.

**Comment by wictorwilen** [comment]
@pschaeflein - love it. Keep it coming!

**Comment by wictorwilen** [comment]
@pschaeflein  - if you have time, please update with this new version

**Comment by wictorwilen** [comment]
Documentation is now added into the Wiki

**Comment by wictorwilen** [comment]
Closing this one, as we will always need more docs :-)

**Comment by cagdasdavulcu** [comment]
It would be great if we can document the SharePoint Tab Configuration :)

**Comment by wictorwilen** [comment]
@cagdasdavulcu - like this? https://github.com/pnp/generator-teams/wiki/Build-a-SharePoint-Online-Provider-Hosted-Web-Part

**Comment by cagdasdavulcu** [comment]
@wictorwilen yes. The property tabSharePoint was unclear during the implementing integration tests, how to use the property. thank you!
