### ISSUE TITLE
Add support for Teams JS SDK 1.11

### ISSUE THREAD

**Issue by wictorwilen** [pnp/generator-teams#241]
### 💡 Idea

Replace Teams JS SDK 1.10 with 1.11

### Is your feature related to a bug

no

### Alternatives

n/a

**Comment by sudo-elia** [comment]
Hey, can i update the versions?

**Comment by appieschot** [comment]
@twopill awesome! All yours! Let us know if you need any help.

**Comment by stephanbisser** [comment]
As the PR is now merged, I guess we can close the issue. Thanks @twopill for your contribution!
