### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by wictorwilen** [pnp/generator-teams#25]
Configure project for CI (Travis?)

**Comment by waldekmastykarz** [comment]
If you like, I could help you setup CI using CircleCI the same way we have it for the Office 365 CLI and SPFx controls

**Comment by wictorwilen** [comment]
We added Travis CI a couple of months ago, to verify builds. I'd love to extend this to automatic npm publishing - so feel free to contribute.

**Comment by waldekmastykarz** [comment]
I don't know Travis but would be happy to walk you through what we have in the CLI for automatic publishing to npm. We publish @next from dev and @version following the tag on the master branch. Would that be something that you'd like to use or would you prefer only automated releases and manual beta versions?

**Comment by wictorwilen** [comment]
I'm game!

**Comment by wictorwilen** [comment]
Improved CI, using Travis is implemented in 2.7.0@preview
