### ISSUE TITLE
In generated manifest.json, the "commandLists" node is incorrect.

### ISSUE THREAD

**Issue by pschaeflein** [pnp/generator-teams#26]
Generator version 2.2.1-preview

Generated node is "commandList"
Correct node is "commandLists"  (plural)

**Comment by wictorwilen** [comment]
@pschaeflein - can you please check this. Cannot repro this, and the deployed code in 2.2.1-preview looks correct

**Comment by pschaeflein** [comment]
Confirmed. Fresh install of generator is fixed.
