### ISSUE TITLE
Add support disclaimer to docs

### ISSUE THREAD

**Issue by appieschot** [pnp/generator-teams#285]
We should add a disclaimer to Generator Teams docs that clearly state that YoTeams is not a Microsoft product and not a subject to any SLA. 

Here's a similar snippet from PnP PowerShell:

> This library is open-source and community provided library with active community providing support for it. This is not Microsoft provided module so there's no SLA or direct support for this open-source component from Microsoft. Please report any issues using the [issues list](https://github.com/pnp/generator-teams/issues).

Similar issue at https://github.com/pnp/cli-microsoft365/issues/3047

**Comment by RickVanRousselt** [comment]
Merged into the preview branch. Let's close this when it's released

**Comment by wictorwilen** [comment]
Deployed - thanks @RickVanRousselt
