### ISSUE TITLE
Bug report: Error when running 'yo teams' (requirer 3.0.0 but I have 3.1.1)

### ISSUE THREAD

**Issue by adambu** [pnp/generator-teams#288]
### Description

I installed all the prereqs found at https://github.com/pnp/generator-teams/blob/master/docs/docs/user-guide/setup-machine.md, but when I run 'yo teams' I get this:
> This generator (teams:app) requires yeoman-environment at least 3.0.0, current version is 2.10.3, try reinstalling latest version of 'yo' or use '--ignore-version-check' option

Here's my "npm -g outdated" output:

Package                          Current  Wanted  Latest  Location
@microsoft/generator-sharepoint   1.11.0  1.11.0  1.13.1
create-react-app                   3.3.0   3.3.0   5.0.0
ejs-lint                           1.1.0   1.1.0   1.2.1
nodemon                            2.0.3   2.0.3  2.0.15
yo                                 3.1.1   3.1.1   4.3.0

### Steps to reproduce

1. Follow the steps at https://github.com/pnp/generator-teams/blob/master/docs/docs/user-guide/setup-machine.md
2. Run 'yo teams'

### Expected results

Teams generator should run.

### Actual results

Error
> This generator (teams:app) requires yeoman-environment at least 3.0.0, current version is 2.10.3, try reinstalling latest version of 'yo' or use '--ignore-version-check' option

### Project you experience issues with

generator-teams

### generator version

3.5.0

### build tools version

1.5.0

### nodejs version

v16.14.0

### npm version

v10.13.0

### Operating system (environment)

Windows

### Additional Info

When I try the suggested --ignore-version-check option, I get 'Maximum callstack size exceeded'

**Comment by wictorwilen** [comment]
Thanks @adambu for reporting this. As you can see in your `npm -g outdated` results, you have version `3.1.1` of `yo`, and the latest version of `yo` is `4.3.3`, and this is likely your issue. Please update the global version of `yo`, to the latest version.

**Comment by RickVanRousselt** [comment]
Updated the documentation to include the following on the setup machine page

If you get this error:
> This generator (teams:app) requires yeoman-environment at least 3.0.0, current version is 2.10.3, try reinstalling latest version of 'yo' or use '--ignore-version-check' option

and you run `npm -g outdated` you will notice that you are not running the latest version of the yeoman generator. You need to update your global package of yo using `npm install yo@latest -g`. To update to the latest version of the gulp CLI use `npm install gulp-cli@latest -g`

@adambu Let us know if this solution works?

**Comment by adambu** [comment]
Thank @wictorwilen and @RickVanRousselt.   Yes, it did work!  I guess I should have tried that, but the error is, of course, misleading.  @RickVanRoussel.  Can you mention which exact documentation you updated?  And on the subject of documentation, please note that the two links at the top of **[https://github.com/pnp/generator-teams/blob/master/docs/docs/tutorials/build-your-first-microsoft-teams-app.md](url)**, including the one to "all the prerequisites" are broken. <<edit sorry forgot to finish the sentence there>>

**Comment by stephanbisser** [comment]
Links are working as expected and issue should be resolved, therefore closing this.
