### ISSUE TITLE
Bug report: Build a SharePoint Online Provider Hosted Web Part Tutorial doesn't seem to work with ngrok.

### ISSUE THREAD

**Issue by adambu** [pnp/generator-teams#293]
### Description

When I do the tutorial here: https://github.com/pnp/generator-teams/blob/master/docs/docs/tutorials/build-a-sharepoint-online-provider-hosted-web-part.md
...everything seems to work fine (no build or deployment errors), but when I try to add the web part to a page (comes up fine in list of available web parts), it just doesn't show up.  ngrok is running and URLs are resolving as expected.  

When I try to add it to a classic page (under miscellaneous category), I see the configuration page, but it doesn't take a value in the form (button doesn't submit).

### Steps to reproduce

1. Follow the steps exactly on https://github.com/pnp/generator-teams/blob/master/docs/docs/tutorials/build-a-sharepoint-online-provider-hosted-web-part.md.  I created a new site using a modern Teams site template.

2. Add to a site page or Add an App  

### Expected results

When adding to a site page, either the configuration page should show, or the Web Part should show in full page orientation.

When adding as an app, I should see the web part in the list of available apps under "from your organization."

### Actual results

When adding the web part to a site page, the "SharePoint Tab" app is available, but it doesn't render anything (no configuration or web part).

When trying to add it as an app, it does not show up under "from your organization."

### Project you experience issues with

generator-teams

### generator version

3.5.0

### build tools version

1.6.0

### nodejs version

v16.14.0

### npm version

8.3.1

### Operating system (environment)

Windows

### Additional Info

I'm also interested to know the exact use case this is trying to demonstrate.  Are we just showing how to upload the app to SharePoint App Catolog, and then we can also upload to the Team app catalog?  Is it to show that a PHA (e.g. nodejs app) can be used both in SharePoint and Teams?  If so, shouldn't there be a little bit in the tutorial about that?

**Comment by wictorwilen** [comment]
Thanks @adambu - we'll try to replicate this and see what is happening. This tutorial is written many moons ago and things (in SharePoint) has moved around a bit since then.

**Comment by adambu** [comment]
FYI, I also tried to upload the demo app from here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint.  I assume this is the same basic scenario.  Neither the app I built, nor the demo app worked in SharePoint Online, but both more or less worked in Teams.  If I had to guess it might have something to do with manifest version or something.

**Comment by wictorwilen** [comment]
@adambu - I've done some investigation on this...

1) By following the tutorial (yes, it's not updated with the latest generator...working on it) I get the app to properly deploy to SharePoint
2) I can add it as a new page (full page experience) and as a web part 
3) **BUT** I needed to add some code to enable the *Save* button in the config dialog - since the `useTeams()` hook does not return the `context` when hosted in SharePoint.

This is the code I needed to add/modify, see the else statement:

``` TypeScript
useEffect(() => {
        if (context) {
            setText(context.entityId);
            entityId.current = context.entityId;
            microsoftTeams.settings.registerOnSaveHandler(onSaveHandler);
            microsoftTeams.settings.setValidityState(true);
            microsoftTeams.appInitialization.notifySuccess();
        } else {
            microsoftTeams.initialize();
            microsoftTeams.getContext( c =>{
                setText(c.entityId);
                microsoftTeams.settings.registerOnSaveHandler(onSaveHandler);
                microsoftTeams.settings.setValidityState(true);
            });
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [context]);
```

Also, wrt your comment on use case - I'll update the docs with that...
