### ISSUE TITLE
Bug report: Cancel/Save buttons don't appear

### ISSUE THREAD

**Issue by samctrumpet** [pnp/generator-teams#299]
### Description

I've been following the documentation for setting up a custom connector here: https://docs.microsoft.com/en-us/learn/modules/msteams-webhooks-connectors/7-exercise-o365-connectors

The person opens up to configure the connector and it looks like:
![image](https://user-images.githubusercontent.com/95428078/156362346-e4fe9ee8-fa57-4055-8bcf-3c2289ecc402.png)

After following the exact instructions, when I open up to configure the connector it looks like:
![image](https://user-images.githubusercontent.com/95428078/156362514-85862386-e70b-4db0-8fab-1774b8dad3dd.png)

### Steps to reproduce

I've followed the exact instructions.

### Expected results

That there is a Cancel/Save button.

### Actual results

There is no Cancel/Save button

### Project you experience issues with

generator-teams

### generator version

3.5.0 and 3.1.0 

### build tools version

1.6.0

### nodejs version

v16.13.1

### npm version

8.1.2

### Operating system (environment)

Windows

**Comment by wictorwilen** [comment]
The *Save* and *Cancel* buttons are part of the Microsoft Teams app, and not produced by your application configuration page. Are you doing this in a browser? Try resetting your Zoom settings (`ctrl+0`)?

**Comment by samctrumpet** [comment]
@wictorwilen apologies, I've since found another person who raised this issue on the Microsoft JS SDK github,
https://github.com/OfficeDev/microsoft-teams-library-js/issues/970

I'll close this!

**Comment by wictorwilen** [comment]
Thanks for the update @samctrumpet
