### ISSUE TITLE
Small typo in README.md in generator

### ISSUE THREAD

**Issue by Laskewitz** [pnp/generator-teams#3]
There is a small typo in the README.md in the generator at line 42:

> 4. Go to the created Web App and configure *Deployment Credentials*. Not that this is only done once per Microsoft Azure Account.

I think you meant:

> 4. Go to the created Web App and configure *Deployment Credentials*. Note that this is only done once per Microsoft Azure Account.

**Comment by wictorwilen** [comment]
Thanks Daniel! Merged and closed!
