### ISSUE TITLE
Trying to add TDD aproach fail

### ISSUE THREAD

**Issue by christosmito** [pnp/generator-teams#308]
I am trying to implement TDD aproach on custom app in order to test the endpoints I am building on. But I am getting an error trying to import the server.ts. Let me mention that I am not familiar with typescript, only with javascrip and my question might be silly. I ask a question on github under this link: https://stackoverflow.com/questions/71690968/import-ts-file-fails-with-no-overload-matches-this-call which describes the error I get and my code. 
Thanks in advance!

**Comment by RickVanRousselt** [comment]
Hi @christosmito 

This would need to be added to the documentation. There are numerous development patterns that exist and we cannot create documentation around all of them. If you are open to it then we would love to have you investigate this and write a how-to on this topic and make a pull request on the documentation.

For now, we are closing this issue because of time constraints.

**Comment by christosmito** [comment]
I would glad to write a documentation about TDD for this app but I dont know how to implement this. If you give me any guide would be wonderful. In general I would like to contribute to the community.
________________________________
Από: Rick Van Rousselt ***@***.***>
Στάλθηκε: Παρασκευή, 16 Σεπτεμβρίου 2022 12:22 μμ
Προς: pnp/generator-teams ***@***.***>
Κοιν.: christosmito ***@***.***>; Mention ***@***.***>
Θέμα: Re: [pnp/generator-teams] Trying to add TDD aproach fail (Issue #308)


Hi @christosmito<https://github.com/christosmito>

This would need to be added to the documentation. There are numerous development patterns that exist and we cannot create documentation around all of them. If you are open to it then we would love to have you investigate this and write a how-to on this topic and make a pull request on the documentation.

For now, we are closing this issue because of time constraints.
