### ISSUE TITLE
Error package lint when generating new teams app

### ISSUE THREAD

**Issue by alexandrenovo2001** [pnp/generator-teams#322]
### Description

![Screenshot 2022-06-30 230900](https://user-images.githubusercontent.com/60365638/176787147-f7fc9b29-1fef-4847-80d7-597f31690fe6.jpg)

### Steps to reproduce

run yo teams command
fill all the inputs with default values

### Expected results

project to be generator

### Actual results

Error when downloading lint package

### Project you experience issues with

generator-teams

### generator version

4.0.1

### build tools version

1.7.0

### nodejs version

v16.14.0

### npm version

8.5.0

### Operating system (environment)

Windows

**Comment by wictorwilen** [comment]
Unable to repro this, please try to scaffold the solution again.

The confusing part is `eslint@8.4.5`  - that package version does not exist. And `generator-teams` scaffolds with version `8.15.0` or later and there's no reference in a dependency to `8.4.5`

**Comment by RickVanRousselt** [comment]
@alexandrenovo2001 Any update on this? Did you scaffold the solution again?
