### ISSUE TITLE
Audio recorder bot

### ISSUE THREAD

**Issue by LYDE1234** [pnp/generator-teams#332]
We want to create a bot that can record voice from Teams meetings and stream / upload them to AWS S3 for later transcription. Can you point us to a sample or documentation that can help us do this - I've followed a basic tutorial on how to use the #YoTeams for a chatbot but it's not clear to me how to extend to recording bot?

**Comment by stephanbisser** [comment]
@LYDE1234 this is a super specific topic and we do not have a yo teams tutorial/sample/documentation for that, but I would recommend you take a look at [this docs article](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview) which explains the topic and includes links to samples as well.

**Comment by RickVanRousselt** [comment]
Hi @LYDE1234 
This is called a media bot, and it's only available in C# even. So also take a look into [this](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots).

**Comment by appieschot** [comment]
Closed issue, feel free to re-open if you feel we should add additional documentation if the pointed solutions do not provide enough clarity.
