### ISSUE TITLE
Manifest version/schema mismatch

### ISSUE THREAD

**Issue by coatsy** [pnp/generator-teams#38]
The manifest generated by the generator starts with:
```
"$schema": "https://statics.teams.microsoft.com/sdk/v1.2/manifest/MicrosoftTeams.schema.json",
"manifestVersion": "1.0",
```
Which appears to stop the manifest from being loaded by either the teams client (when sideloading) or App Studio (when importing the package)
Fix appears to be updating the manifest version:
```
"$schema": "https://statics.teams.microsoft.com/sdk/v1.2/manifest/MicrosoftTeams.schema.json",
"manifestVersion": "1.2",
```

**Comment by wictorwilen** [comment]
Thanks for noticing, I've not seen this happening before - but for sure it makes sens to have the schema and manifest version to match.

**Comment by wictorwilen** [comment]
@coatsy - can you please test with the new preview

> npm install generator-teams@preview --global

**Comment by coatsy** [comment]
Yup - resolved in latest preview
