### ISSUE TITLE
Older version of botbuilder-teams installed

### ISSUE THREAD

**Issue by coatsy** [pnp/generator-teams#39]
This generator installs botbuilder-teams v0.1.7. 
On my system, bot won't return anything until I update to v0.2.1

**Comment by wictorwilen** [comment]
Thanks @coatsy - I recently noticed this as well and only fixed it for the upcoming release. Will make an intermediate release for this combined with a few other minor fixes.

**Comment by wictorwilen** [comment]
@coatsy - can you please test with the new preview

> npm install generator-teams@preview --global

**Comment by coatsy** [comment]
Resolved in latest preview
