### ISSUE TITLE
dotenv with imports does not work

### ISSUE THREAD

**Issue by doxxx** [pnp/generator-teams#44]
The template uses the following pattern in server.ts to load env vars before initializing the app:

```typescript
require('dotenv').config();
import * as allComponents from './TeamsAppsComponents';
```

However, this does not work because all imports are resolved first before any top-level code is executed in the file. Thus, a bot component imported via `TeamsAppsComponents`, which uses the `@BotDeclaration` wrapper to provide the app ID and password from `process.env`, will not find those env vars.

The workaround is to modify the gulpfile's nodemon task to pass `--require dotenv/config` as node args.

**Comment by wictorwilen** [comment]
Thanks for your comment. In fact it is working, TypeScript converts the import to a `require` statement which is required inline and assigned to a variable/const (`allComponents`) which in turn will invoke the declarators. So switching the order of those will not work. 

You can do an easy test by adding a simple log statement into the bot constructor and log the value of the connector (for instance `log(this.Connector);`). With the order above you will see that `botConnectorAudience` has a value, but if you change the order the value of it will be `undefined`.

Is your experience different? If so, do you use any other versions of TypeScript or Webpack?

**Comment by doxxx** [comment]
I stepped through it with a debugger as well as log statements. The import was definitely being processed before dotenv was being invoked.

I went digging because my bot's replies had mysteriously stopped working. There were no errors being logged to the console but when I stepped through it with a debugger, the Teams REST API was returning a 401 Unauthorized response when the bot tried to send a reply. When I looked back at the `botSettings` in the debugger, the `appId` and `appPassword` fields were empty. I added logging just before the bot class definition to show the env variables and they were not set either.

I'm using Typescript 3.1.2 and Webpack 4.16.3. I believe that's a newer version of Typescript than what the generator originally used. I upgraded it because I wanted some React-related features like element fragments (`<></>`).

**Comment by wictorwilen** [comment]
Tried with Typescript 3.1.2 and 3.1.3 and still can't reproduce it. Have you made any other project changes (TS or Webpack config or gulp file changes?). Could you share your code?

**Comment by doxxx** [comment]
Turns out it was my mistake. I had another import before the `require('dotenv')` that was in turn importing the bot class. Once I moved that import next to the `TeamsAppComponents` import, it fixed the load order.

Sorry for the false alarm!

**Comment by wictorwilen** [comment]
Thanks for the update, feel free to add any new issues you find! And thanks for using the generator!
