### ISSUE TITLE
Adding sample unit tests in generator templates

### ISSUE THREAD

**Issue by cagdasdavulcu** [pnp/generator-teams#48]
Hello Wictor,

Enhancement:
it would be a good idea to add sample unit tests in generator templates.

Best Regards,
Cagdas Davulcu

**Comment by wictorwilen** [comment]
Agree! And feel free to contribute!

**Comment by wictorwilen** [comment]
@cagdasdavulcu - please take a look at the new `2.7.0-preview` version that has some refactoring. If you want to stub out some initial unit tests, please do. I'd prefer using Jest for testing framework, thoughts?

**Comment by cagdasdavulcu** [comment]
@wictorwilen - i would also prefer to use Jest Framework. 

I can provide the setup for Jest framework and one simple unit test for a specific project template to reduce merging efforts

After that we can extend the test samples with the following test types:
-> Mocking Sample
-> Snapshot Testing Sample (with react-test-renderer or enzyme - we can decide it together)

Please give me feedback if this approach o.k. for you. And the other ideas are welcome!

**Comment by wictorwilen** [comment]
@cagdasdavulcu go, go, go!

**Comment by cagdasdavulcu** [comment]
We can categorize the tests as:
- Server-Side Tests
- Client-Side Tests (currently tests for client-side components of Tab Apps are supported)

Next steps:
- Analyzing the project types and find out, on which projects the client-side tests are needed and implement full test support for client-side components
- Analyzing project file structure for locating server-side tests
- Starting to support tests for server-side components

**Comment by cagdasdavulcu** [comment]
From my point of view it makes sense to split some of react components (like connector compoenent) as presentational and container components for better unit testing support. But it is not a high priority task :)

**Comment by cagdasdavulcu** [comment]
@wictorwilen can you please move this task to V3? Because of the dependence to refactoring for the V3, i wouldn't invest time for this task.

**Comment by wictorwilen** [comment]
Closing this as unit tests been re-factored in 3.0.0 (#176). We should rather open individual issues around more exhaustive testing of artefacts
