### ISSUE TITLE
Ignoring of generators folder

### ISSUE THREAD

**Issue by cagdasdavulcu** [pnp/generator-teams#53]
i would suggest, that we should ignore the generators folders in .git file and generate it via. build server, thereby we have less conflicts on pull requests. [Enhancement]

**Comment by wictorwilen** [comment]
Was committed the other day in https://github.com/OfficeDev/generator-teams/commit/d83040b7896506a92e60b58770c9ee9c7db4e369

**Comment by cagdasdavulcu** [comment]
![image](https://user-images.githubusercontent.com/1059729/55505165-cbeb1900-5652-11e9-8fe5-0d9c5d8a2fb0.png)

i'm seeing the generators folder in .gitignore file but these of files will not be ignored on windows
