### ISSUE TITLE
Tab project cannot be compiled on 2.7.0-preview3

### ISSUE THREAD

**Issue by cagdasdavulcu** [pnp/generator-teams#54]
TS2322: Type '{ theme: ThemeStyle; fontSize: number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Test07Tab> & Readonly<ITest07TabProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'theme' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Test07Tab> & Readonly<ITest07TabProps> & Readonly<{ children?: ReactNode; }>'

**Comment by wictorwilen** [comment]
Fixed in `2.7.0-preview4` (da75026f1944a500aa1b134f978a7564ca18a02e). Thanks for reporting AND fixing!
