### ISSUE TITLE
Generated MessageExtension: non static host

### ISSUE THREAD

**Issue by RalfBrennscheidt** [pnp/generator-teams#58]
Hi,

shouldn't the generated MessageExtension rather use the HOSTNAME from the .env instead of a static one which is being asked during the generation ?

If you switch the host in .env when doing local testing or debugging with ngrok it still uses the static value you entered in the initial generation process.

File: /src/messageExtension/templates/src/app/{messageExtensionName}/{messageExtensionClassName}.ts
Line: 15 + 43

**Comment by wictorwilen** [comment]
Good catch! Committed locally and will push soon, checking all other places as well.

**Comment by wictorwilen** [comment]
Fixed in 25a9e9fcbebcb594aa47fdfc9cdf555c0b798696 
Please install the latest preview package to verify it.
Thanks for reporting this and making #yoteams even better!
