### ISSUE TITLE
Add a selection of schema version

### ISSUE THREAD

**Issue by cagdasdavulcu** [pnp/generator-teams#62]
1.3
devPreview

**Comment by wictorwilen** [comment]
See #63

**Comment by cagdasdavulcu** [comment]
@wictorwilen another feature idea: Manifest upgrade v1.3 -> devPreview

**Comment by wictorwilen** [comment]
Included in version 2.7.1 (7c45f921ef44af81a909295724a4dd387f4bc1e1)
