### ISSUE TITLE
Add support for ngrok in the build pipeline

### ISSUE THREAD

**Issue by cagdasdavulcu** [pnp/generator-teams#66]
gulp ngrok-serve

**Comment by cagdasdavulcu** [comment]
We can also design it to update messaging endpoint of bot channel registration via. gulp process and auto side loading of teams package in teams.

With current implementation are the following steps supported:
- run ngrok
- get url of ngrok tunnel
- extract host name from url
- set host name to process.env.HOSTNAME
- generate manifest file 
------> FEATURE: as next we can side load it in teams - we should design the teams access)
------> FEATURE: register the package in a teams channel
- serve the express application
- FEATURE: Change the bot channel registration  in azure via. Azure AD App

Then we have no manual processes for debugging the teams application.

**Comment by wictorwilen** [comment]
Included in version 2.7.1 (7c45f921ef44af81a909295724a4dd387f4bc1e1)
