### ISSUE TITLE
Required "guid" module missing

### ISSUE THREAD

**Issue by sebastienlevert** [pnp/generator-teams#7]
As soon as we install globally the generator on Windows 10 and try to run the generator using "yo teams-tab", an error is thrown stating that the "guid" module is missing.

![image](https://cloud.githubusercontent.com/assets/7620955/23774961/4e6a7e0a-04f4-11e7-9ab1-56d428057aa7.png)

When installing the guid module (npm install guid --global), it starts to work again.

**Comment by wictorwilen** [comment]
Thanks for finding this. Issue is now fixed!
