### ISSUE TITLE
 The provided value "./dist/web/scripts" is not an absolute path!

### ISSUE THREAD

**Issue by laneyvb** [pnp/generator-teams#8]
I'm getting an error when running the webpack build "The provided value "./dist/web/scripts" is not an absolute path , same for /dist "
I've found that can be worked around via appending __dirname + in the right place in the webpack.config.
Couldn't see any contribution guidelines so figured would log it as a bug, but happy to fork and submit as pull request if that is helpful.

**Comment by wictorwilen** [comment]
Thanks Elaine, I'd love a PR for this. Go ahead!

**Comment by wictorwilen** [comment]
Resolved with PR #9
