### ISSUE TITLE
Unable to create messageextention

### ISSUE THREAD

**Issue by KbWorks** [pnp/generator-teams#80]
**Describe the bug**
Creating a new message extention with a new bot stops reacting when you have to select new bot or existing bot. Seems there is no args catch

**To Reproduce**
yo teams
choose message extention
![image](https://user-images.githubusercontent.com/14150615/59859481-0b392400-937d-11e9-872b-c378e0219490.png)

create a bot.. 

 - Generator version: 2.9.1
 - OS: MacOS
 - Node version: [10.16.0]

**Comment by StfBauer** [comment]
@KbWorks what yo version are you using? Seems like there is an [issue with the inquirer](https://github.com/SBoudrias/Inquirer.js/issues/811) package yeoman in version 2.x.x.

To solve this issue downgrade to yo version 1.8.5, the latest that use an older inquirer version.

```sh
npm install yo@1 -g
```

**Comment by wictorwilen** [comment]
I think I've seen that on node 10. Try with node 8 and see what happens.

(There's also several issues related to Yeoman testing with node 10)

**Comment by wictorwilen** [comment]
@KbWorks - I'm unable to replicate this using Windows 10 and node 10.16.0

**Comment by StfBauer** [comment]
Like I mentioned before there was a bug with the inquirer package for 24 hours.

**Comment by wictorwilen** [comment]
@KbWorks - have you had a chance to try @StfBauer suggestion?

**Comment by wictorwilen** [comment]
Closing this one, due to lack of response/feedback. Feel free to open again if the issue happens again
