### ISSUE TITLE
Gulp manifest fails using manifest schema 1.5 fails validation

### ISSUE THREAD

**Issue by CameronDwyer** [pnp/generator-teams#81]
**Describe the bug**
Gulp manifest using schema 1.5 fails validation

The generated manifest has an empty "localizationInfo": {}
This requires a defaultLanaguageTag

**To Reproduce**
Generate project selecting manifest schema 1.5
Run Gulp manifest

**Expected behavior**
Gulp manifest command to succeed and the generated manifest.json to pass validation

**Detailed information**
 - Generator version: 2.11
 - OS: Windows
 - Node version: 10.16.2
 - Npm version: 6.9.0

![image](https://user-images.githubusercontent.com/16345690/63014310-9512f280-bed1-11e9-8786-071e7bd08772.png)

**Comment by wictorwilen** [comment]
Thanks for reporting. Thought that was fixed in the released version (`2.11.0`), the bug existed in the preview. Will verify and get back shortly. Meanwhile, all you need to do is to remove the `localizationInfo` node in the json file

**Comment by CameronDwyer** [comment]
Thanks - wasn't a blocker just wanted to report it.

**Comment by wictorwilen** [comment]
Found the issue. Working on a quick fix and adding it to the test suite

**Comment by wictorwilen** [comment]
`2.11.1` - available soon through npm will solve the issue going forward

**Comment by CameronDwyer** [comment]
Wow, that was an incredibly quick fix :-)
