### ISSUE TITLE
How to debug an msteams bot?

### ISSUE THREAD

**Issue by uioporqwerty** [pnp/generator-teams#82]
I followed the instructions in the readme for setting up debugging for a bot and my launch.json looks like this.

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 5858,
      "sourceMaps": true,
      "outFiles": ["${workspaceRoot}/dist/**/*.js"],
      "remoteRoot": "${workspaceRoot}/src/"
    }
  ]
}
```

If I run `gulp serve --debug` then I am not able to start a debugging session and it stops immediately. I noticed the gulp serve command said the debugger was listening on port 9229 and if I switch to that port number then I am able to attach but it says that all breakpoints are unverified and I am not able to hit them. How can I debug a bot using this generator?

**Comment by uioporqwerty** [comment]
Solved. I used this to get some insight into node debugging: https://code.visualstudio.com/docs/nodejs/nodejs-debugging

My final configuration looks like this after removing the remoteRoot entry:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 9229,
      "sourceMaps": true,
      "outFiles": ["${workspaceFolder}/dist/**/*.js"],
      "restart": true
    }
  ]
}
```

**Comment by wictorwilen** [comment]
Thanks @uioporqwerty - glad you sorted it out
