### ISSUE TITLE
Getting error  Missing required property: defaultLanguageTag

### ISSUE THREAD

**Issue by arujindal123** [pnp/generator-teams#85]
**Describe the bug**
I have created a Teams App and trying to run gulp ngrok-serve command. 
This is giving error as shown below:
![image](https://user-images.githubusercontent.com/17233483/65449794-50c42c00-de59-11e9-92d3-f8fcb23950e6.png)

[23:13:30] Starting 'ngrok-serve'...
[23:13:30] Starting 'start-ngrok'...
[23:13:30] [NGROK] starting ngrok...
[23:13:36] [NGROK] Url: https://4dfe1e9f.ngrok.io
[23:13:36] [NGROK] You have been assigned a random ngrok URL that will only be available for this session. You wil need to re-upload the Teams manifest next time you run this command.
[23:13:36] [NGROK] HOSTNAME: 4dfe1e9f.ngrok.io
[23:13:36] Finished 'start-ngrok' after 6.18 s
[23:13:36] Starting 'manifest'...
[23:13:36] Starting 'validate-manifest'...
[23:13:36] Starting 'generate-manifest'...
[23:13:36] Finished 'generate-manifest' after 30 ms
[23:13:36] Starting 'schema-validation'...
[23:13:36] Using manifest schema 1.5
[23:13:38] 'schema-validation' errored after 2.05 s
[23:13:38] Error in plugin "validate-manifest"
Message:
    Missing required property: defaultLanguageTag
[23:13:38] 'validate-manifest' errored after 2.09 s
[23:13:38] 'manifest' errored after 2.09 s
[23:13:38] 'ngrok-serve' errored after 8.27 s

**To Reproduce**
1. Follow https://camerondwyer.com/2019/09/09/how-to-create-a-microsoft-teams-messaging-extension-pop-up-dialog-with-a-custom-ui/ to create Teams App.
2. Run gulp ngrok-serve 
3. See error

**Comment by wictorwilen** [comment]
This is a normal error and will happen by design if you have an *invalid schema*. like you have the `localizationInfo` set in your `manifest.json` without the `defaultLanguageTag`.

1) What version of the generator do you have now?
2) What version of the generator was used to create the project, if it was different than the one now?

**Comment by arujindal123** [comment]
I am using 2.11.1 and it is the same version on which project was created.

**Comment by arujindal123** [comment]
Removed localizationinfo since dont need localization in App and now its working. Thanks.

**Comment by wictorwilen** [comment]
Please share your `manifest.json`. DId you run the generator multiple versions? Did you select to use localization/translations?

**Comment by arujindal123** [comment]
I created new Teams App with below configuration 
![image](https://user-images.githubusercontent.com/17233483/65482020-4d5e8e00-deb5-11e9-9b9b-aa569c643821.png)

Once it's created run gulp ngrok-serve and got below error:
![image](https://user-images.githubusercontent.com/17233483/65482054-623b2180-deb5-11e9-8de6-7582fa4b476d.png)



manifest.json

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "id": "0780b450-de86-11e9-b5d6-e5dd87598b55",
  "version": "0.0.1",
  "packageName": "test",
  "developer": {
    "name": "Avanade",
    "websiteUrl": "https://ca9c2e6a.ngrok.io",
    "privacyUrl": "https://ca9c2e6a.ngrok.io/privacy.html",
    "termsOfUseUrl": "https://ca9c2e6a.ngrok.io/tou.html"
  },
  "name": {
    "short": "Teams Hackathon",
    "full": "Teams Hackathon"
  },
  "description": {
    "short": "TODO: add short description here",
    "full": "TODO: add full description here"
  },
  "icons": {
    "outline": "icon-outline.png",
    "color": "icon-color.png"
  },
  "accentColor": "#D85028",
  "configurableTabs": [],
  "staticTabs": [
    {
      "entityId": "default-data",
      "name": "Teams Hackathon",
      "contentUrl": "https://ca9c2e6a.ngrok.io/teamsHackathonTab/",
      "scopes": [
        "personal"
      ]
    }
  ],
  "bots": [],
  "connectors": [],
  "composeExtensions": [],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "ca9c2e6a.ngrok.io"
  ],
  "localizationInfo": {}
}

-----------------------------------------------------

**Comment by wictorwilen** [comment]
As you can see in the screenshot,  you are running `2.11.0-preview` and not `2.11.1` where this is fixed (see #81)
