### ISSUE TITLE
Plumber package depends on minimatch and lodash versions with vulnerabilities

### ISSUE THREAD

**Issue by jsuddsjr** [pnp/generator-teams#86]
**Describe the bug**
Out of the box, the generator should not install packages with known vulnerabilities.

**To Reproduce**
1. Create a new Teams app using default settings.

**Expected behavior**
No vulnerabilities.

**Screenshots**

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  High            Regular Expression Denial of Service

  Package         minimatch

  Patched in      >=3.0.2

  Dependency of   plumber

  Path            plumber > gaze > globule > glob > minimatch

  More info       https://npmjs.com/advisories/118

  High            Regular Expression Denial of Service

  Package         minimatch

  Patched in      >=3.0.2

  Dependency of   plumber

  Path            plumber > gaze > globule > minimatch

  More info       https://npmjs.com/advisories/118

  High            Regular Expression Denial of Service

  Package         minimatch

  Patched in      >=3.0.2

  Dependency of   plumber

  Path            plumber > glob > minimatch

  More info       https://npmjs.com/advisories/118

  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   plumber

  Path            plumber > gaze > globule > lodash

  More info       https://npmjs.com/advisories/577

  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.11

  Dependency of   plumber

  Path            plumber > gaze > globule > lodash

  More info       https://npmjs.com/advisories/782

  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.12

  Dependency of   plumber

  Path            plumber > gaze > globule > lodash

  More info       https://npmjs.com/advisories/1065

  Moderate        Prototype Pollution

  Package         extend

  Patched in      >=2.0.2 <3.0.0 || >=3.0.2

  Dependency of   plumber

  Path            plumber > extend

  More info       https://npmjs.com/advisories/996

**Detailed information**
 - Generator version: [eg 2.5.0]
 - OS: [eg, Windows, MacOS]
 - Node version: [eg 8.10.0]
 - Npm version: [eg. 6.9.0]

**Comment by wictorwilen** [comment]
Please upgrade to version 2.11.1 of the generator and report back with similar issues.

**Comment by jsuddsjr** [comment]
> Please upgrade to version 2.11.1 of the generator and report back with similar issues.

That's the version I'm using. I'm sorry I didn't fill in those fields in the trouble report. For some reason, I thought they were already filled in. <facepalm>

**Detailed information**

Generator version: 2.11.1
OS: Windows 10
Node version: 12.9.0
Npm version: 6.11.3

**Comment by wictorwilen** [comment]
The project is using `plumber@0.4.8` which is the latest version of this package, so there's no way of getting rid of these warnings unless we switch that tooling (or the have the publisher of the package publish an updated version). Also, this package is only used during the build process and will not be part of the bundled solution.

With this in mind, it`s currently a tolerable solution and those warnings can be ignored. Of course we're striving on minimizing these issues in upcoming updates.

**Comment by wictorwilen** [comment]
Closing this one. `npm audit` gives (as of 2020-06-08) zero warnings on the generator itself and for a generated project `plumber` is only used during build-time and should not be used in a running solution - which is an acceptable risk.
