### ISSUE TITLE
React componentWillMount deprecated

### ISSUE THREAD

**Issue by jsuddsjr** [pnp/generator-teams#87]
**Describe the bug**
Running tests produces a warning.

**To Reproduce**
1. Create default site with generator.
2. npm run tests

**Expected behavior**
Tests pass without warnings.

**Screenshots**

      Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
      
      * Move code with side effects to componentDidMount, and set initial state in the constructor.

      * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Detailed information**
 - Generator version: [eg 2.5.0]
 - OS: [eg, Windows, MacOS]
 - Node version: [eg 8.10.0]
 - Npm version: [eg. 6.9.0]

**Additional information**

**Comment by jsuddsjr** [comment]
**Detailed information**

Generator version: 2.11.1
OS: Windows 10
Node version: 12.9.0
Npm version: 6.11.3

**Comment by wictorwilen** [comment]
This is a known state of React. React 16 still supports `componentWillMount` and it will be deprecated in React 17. This will be addressed in future versions of the generator.

**Comment by wictorwilen** [comment]
This is now resolved in current preview (`2.17.0-preview`)

**Comment by wictorwilen** [comment]
Completed in `2.17.1`
