### ISSUE TITLE
Request for Botbuilder v 4.6.0 with teams app

### ISSUE THREAD

**Issue by abhixkj** [pnp/generator-teams#89]
Current generator provides bots with v 4.4.0 which is outdated now. MS has all documentation related to botbuilder sdk v 4.6 and above.

It would be nice to have generator with bots using botbuilder framework 4.6.0 and above, along with documentations on how to host the bot generated by generator-teams to azure portal.

**Comment by wictorwilen** [comment]
@abhixkj - yup, this one is in the works!

**Comment by kunalkankariya** [comment]
Does this also mean that we will do away with botbuilder-teams package and move to the botbuilder core SDK 4.6?

**Comment by wictorwilen** [comment]
@kunalkankariya - Yes, botbuilder 4.6 also means the deprecation of `botbuilder-teams` (which never left the beta stage). Existing solutions will still work and I'll ensure we have a nice upgrade guide in the Yo Teams wiki for this  (ie we will not build any automatic upgrade of your code)

**Comment by wictorwilen** [comment]
FYI: We're currently updating and testing the required dependencies to get this to work smoothly, so expect an update on this topic shortly.

**Comment by wictorwilen** [comment]
4.7 is now used in the latest preview version (2.12)
