### ISSUE TITLE
Generated webpack.config.js does not exclude node modules with slashes in their names

### ISSUE THREAD

**Issue by gabrieldeal** [pnp/generator-teams#92]
**Describe the bug**
The `webpack.config.js` generated by the template does not exclude packages in `node_modules` if the package's name contains a forward slash (e.g., `@google-cloud/firestore`).  This breaks `__dirname` and `__filename` for these packages.

In my project, I fixed this by replacing the `fs.readdirSync('node_modules') ` code in `webpack.config.js` with https://www.npmjs.com/package/webpack-node-externals

**To Reproduce**
1. Generate a MS Teams package
2. `npm install @google-cloud/firestore --save`
3. `npm run build`

**Expected behavior**
The `@google-cloud/firestore` source code should not be in `dist/server.js`.

**Detailed information**

 - Generator version: Unknown (we created our project a while ago)
 - OS: Linux
 - Node version: The template was probably ran under Node 8, but we are building our package using Node 10
 - Npm version: Yarn v1.12.3

The bug is here: https://github.com/OfficeDev/generator-teams/blob/52907a4e2cae0fc8e9c1bf873f6891f878a20e6d/src/app/templates/webpack.config.js#L16-L23

**Comment by wictorwilen** [comment]
Thanks for reporting, we will look into this.

**Comment by wictorwilen** [comment]
Fixed in #176 (actually even earlier)
