### ISSUE TITLE
Blank page when installing demo app generated using yo teams.

### ISSUE THREAD

**Issue by ghost** [pnp/generator-teams#94]
Just generated configurable tab demo application without any customization applied. After installing it to teams web aplication got blank popup.
![blank_page](https://user-images.githubusercontent.com/45337095/73656497-e8a01500-4698-11ea-8857-e8d0124e1055.png)

Inspecting network request show xhr error:
![bad_request](https://user-images.githubusercontent.com/45337095/73656521-fa81b800-4698-11ea-9d2b-3a616bcb6a16.png)

{"errorCode":"BadRequest","message":"Failed to execute MS Graph backend request GetGroupSiteRequest. The server failed to respond correctly. Response Code: BadRequest, Reason: Reason: Bad Request, Correlation headers: request-id: 58df5ced-b3f1-42f7-83ac-5084fed3f658\r\nclient-request-id: 58df5ced-b3f1-42f7-83ac-5084fed3f658\r\nx-ms-ags-diagnostic: {\"ServerInfo\":{\"DataCenter\":\"UK South\",\"Slice\":\"SliceC\",\"Ring\":\"4\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"AGSFE_IN_1\"}}\r\nDate: Mon, 03 Feb 2020 13:14:27 GMT\r\n"}

**Detailed information**
 - Generator version: 3.1.1
 - OS: Windows 10.
 - Node version: v8.9.4
 - Npm version: 5.6.0

**Comment by andrewconnell** [comment]
@egklt said:
> Generator version: 3.1.1

Which version? The generator isn't v3. Maybe you listed the version of Yeoman you have installed? What's important is to list the version of the **generator-teams** package.

Also, would help if you could share the URL that triggered the bad request. Look at the **headers** tab in your screenshot... & please provide the complete URL & headers.

**Comment by wictorwilen** [comment]
@egklt - the JavaScript error looks like one of the standard Teams errors. Can you please share a screenshot of the console/log of your application, so we know that we get incoming requests to your tab page?

**Comment by wictorwilen** [comment]
Closing this issue due to no response. Feel free to open again if required.
