### ISSUE TITLE
Upgrade Teams JS SDK => 1.6.*

### ISSUE THREAD

**Issue by andrewconnell** [pnp/generator-teams#96]
**Is your feature request related to a problem? Please describe.**

Microsoft Teams shipped a new SDK v1.6. Currently, you have to upgrade the project's dependency after scaffolding it with yeoman.

**Describe the solution you'd like**

Default project references latest Teams JS SDK.

**Describe alternatives you've considered**

n/a

*Feel free to assign this to me*

**Comment by wictorwilen** [comment]
Good request. I'd like to take a look at not only update the versioning but also how we do page tracking (right now, directly in the HTML files)

**Comment by andrewconnell** [comment]
Page tracking, as in AppInsights? Submitted that as a sperate issue (#97). That's something I was going to address in my if you want me to take that as well.

**Comment by wictorwilen** [comment]
@andrewconnell  - you're correct, that comment belonged on #97

**Comment by wictorwilen** [comment]
Merged in #98 (2.12.0-preview2)
