### ISSUE TITLE
Upgrade usage of AppInsights (server & client)

### ISSUE THREAD

**Issue by andrewconnell** [pnp/generator-teams#97]
**Is your feature request related to a problem? Please describe.**

Not a problem - current implementation of Application Insights uses an updated version of the Node.JS library. In addition, there's no default usage for any of the web components (*which are now in a different library*).

**Describe the solution you'd like**

- Upgrade the server AppInsights usage to leverage the updated package.
- Add default support for the client AppInsights package, including stubbing out "page view" calls for any default pages created.

**Describe alternatives you've considered**

 n/a

*Feel free to assign this to me*

**Comment by wictorwilen** [comment]
Should work now as intended
